"use client";

import { useState, useEffect, useCallback, useRef, type ReactNode } from "react";
import { toast } from "sonner";
import {
  ChevronLeft, ChevronRight, Download, Search, AlertTriangle,
  CheckCircle2, XCircle, Info, ShieldCheck, FileText, Save, Sheet,
  Banknote, Percent, Loader2, Calendar, Filter, Eye, RefreshCw, CopyX, WandSparkles, PencilLine,
  Clock, Inbox, Calculator, SendIcon, ExternalLink, Globe,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel,
  AlertDialogContent, AlertDialogDescription, AlertDialogFooter,
  AlertDialogHeader, AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import {
  previewDgiiExport, downloadDgiiExport, getDgiiCategories,
  triggerBlobDownload, updateDgiiFields, createDgiiSubmission,
  getDgiiPendingSummary, autoGenerateDgiiReport,
  DgiiFormat, DgiiPreviewResult, DgiiPreviewInvoice, DgiiPendingSummary, DgiiAutoGenerateResult,
  validateInvoiceDgii, dgiiVerifyNcf,
} from "@/lib/api/dgii";
import { DgiiSpreadsheetView } from "@/features/dgii/dgii-spreadsheet-view";
import { DgiiValidationBadge } from "@/components/dgii-validation-badge";
import { DgiiErrorReviewWizard } from "@/features/dgii/dgii-error-review-wizard";
import {
  useDgiiReferenceOptions,
  type DgiiReferenceOptions,
} from "@/features/dgii/dgii-reference-options";

// ── Constants ──────────────────────────────────────────────────────────────

const REPORTS: { id: DgiiFormat; label: string; desc: string; color: string; tx: string }[] = [
  { id: "dgii_606", label: "Formulario 606", desc: "Compras de bienes y servicios", color: "text-blue-600 bg-blue-50 border-blue-200", tx: "expense" },
  { id: "dgii_607", label: "Formulario 607", desc: "Ventas y comprobantes emitidos", color: "text-emerald-600 bg-emerald-50 border-emerald-200", tx: "income" },
  { id: "dgii_608", label: "Formulario 608", desc: "Comprobantes anulados", color: "text-red-600 bg-red-50 border-red-200", tx: "any" },
];

const SOURCE_TYPES = [
  { value: "xml", label: "XML (e-CF)" },
  { value: "pdf_text", label: "PDF (texto)" },
  { value: "image_ai", label: "Imagen (AI)" },
  { value: "image_ocr", label: "Imagen (OCR)" },
  { value: "xlsx", label: "Excel / XLSX" },
  { value: "manual", label: "Manual" },
];

const STATUS_CONFIG: Record<string, { label: string; icon: ReactNode; badge: string }> = {
  ok: { label: "Completa", icon: <CheckCircle2 className="size-3" />, badge: "bg-emerald-500/10 text-emerald-600" },
  warning: { label: "Observaciones", icon: <AlertTriangle className="size-3" />, badge: "bg-amber-500/10 text-amber-600" },
  error: { label: "Error", icon: <XCircle className="size-3" />, badge: "bg-red-500/10 text-red-600" },
  missing: { label: "Incompleta", icon: <Info className="size-3" />, badge: "bg-slate-100 text-slate-600" },
  blocked: { label: "NCF confirmado DGII", icon: <ShieldCheck className="size-3" />, badge: "bg-indigo-500/10 text-indigo-700" },
};

function getInvoiceStatus(inv: DgiiPreviewInvoice, _format: DgiiFormat) {
  if (inv.reporting_state === "blocked_confirmed_ncf") return "blocked";
  return inv.validation_status || "ok";
}

function fmtCurrency(n: number | null | undefined) {
  return new Intl.NumberFormat("es-DO", { style: "currency", currency: "DOP", maximumFractionDigits: 0 }).format(n ?? 0);
}

function currentPeriod() {
  const now = new Date();
  return `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}`;
}

function periodLabel(p: string) {
  const months = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Jul", "Agosto", "Sep", "Octubre", "Nov", "Diciembre"];
  const y = p.slice(0, 4), m = parseInt(p.slice(4, 6), 10) - 1;
  return `${months[m]} ${y}`;
}

function prevPeriod(p: string) {
  let y = parseInt(p.slice(0, 4)), m = parseInt(p.slice(4, 6));
  m--; if (m < 1) { m = 12; y--; }
  return `${y}${String(m).padStart(2, "0")}`;
}
function nextPeriod(p: string) {
  let y = parseInt(p.slice(0, 4)), m = parseInt(p.slice(4, 6));
  m++; if (m > 12) { m = 1; y++; }
  return `${y}${String(m).padStart(2, "0")}`;
}

// ── DGII Field definitions per column ──────────────────────────────────

// ── Date input with DD-MM-YYYY display + native picker ─────────────────

function DgiiDateInput({ value, onChange, placeholder, className }: {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  className?: string;
}) {
  const [text, setText] = useState(value ? value.split("-").reverse().join("-") : "");
  const pickerRef = useRef<HTMLInputElement>(null);
  const committed = useRef(true);

  // Sync from external (picker) changes
  useEffect(() => {
    if (committed.current) {
      setText(value ? value.split("-").reverse().join("-") : "");
    }
  }, [value]);

  const handleTextChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    committed.current = false;
    const raw = e.target.value.replace(/[^0-9]/g, "");
    let formatted = raw;
    if (raw.length > 2) formatted = raw.slice(0, 2) + "-" + raw.slice(2);
    if (raw.length > 4) formatted = formatted.slice(0, 5) + "-" + formatted.slice(5);
    setText(formatted);
    // Auto-commit when complete dd-mm-yyyy
    if (/^\d{2}-\d{2}-\d{4}$/.test(formatted)) {
      const [d, m, y] = formatted.split("-");
      committed.current = true;
      onChange(`${y}-${m}-${d}`);
    }
  };

  return (
    <div className={cn("relative", className)}>
      <Calendar
        className="absolute left-2 top-1/2 size-3 -translate-y-1/2 text-muted-foreground cursor-pointer"
        onClick={() => pickerRef.current?.showPicker()}
      />
      <input
        type="text"
        value={text}
        onChange={handleTextChange}
        placeholder={placeholder || "DD-MM-YYYY"}
        className="flex h-8 w-full rounded-md border border-input bg-transparent pl-7 pr-2 text-xs shadow-xs transition-[color,box-shadow] outline-none placeholder:text-muted-foreground/50 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50"
        onFocus={(e) => { const inp = e.target; setTimeout(() => inp.select(), 0); }}
      />
      <input
        ref={pickerRef}
        type="date"
        value={value}
        onChange={(e) => { committed.current = true; onChange(e.target.value); }}
        className="absolute inset-0 opacity-0 pointer-events-none"
        tabIndex={-1}
        aria-hidden
      />
    </div>
  );
}

// ── Inline Field Editor ────────────────────────────────────────────────────

function FieldInput({ label, value, onChange, type = "text", placeholder }: {
  label: string; value: string | number | null | undefined;
  onChange: (v: string) => void; type?: string; placeholder?: string;
}) {
  return (
    <div className="flex flex-col gap-0.5">
      <label className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</label>
      <Input
        type={type}
        value={value ?? ""}
        onChange={e => onChange(e.target.value)}
        className="h-7 text-xs font-mono"
        placeholder={placeholder}
        onClick={e => e.stopPropagation()}
      />
    </div>
  );
}

function FieldSelect({ label, value, onChange, options }: {
  label: string; value: string | null | undefined;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
}) {
  const hasValueOption = !!value && options.some((option) => option.value === value);
  const resolvedOptions = !hasValueOption && value
    ? [{ value, label: value }, ...options]
    : options;

  return (
    <div className="flex flex-col gap-0.5" role="presentation" onClick={e => e.stopPropagation()}>
      <label className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</label>
      <Select value={value || ""} onValueChange={onChange}>
        <SelectTrigger className="h-7 text-xs">
          <SelectValue placeholder="Seleccionar..." />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="__none">— Sin valor —</SelectItem>
          {resolvedOptions.length > 0
            ? resolvedOptions.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))
            : (
              <SelectItem value="__empty" disabled>
                Sin opciones disponibles
              </SelectItem>
            )}
        </SelectContent>
      </Select>
    </div>
  );
}

function DgiiFieldEditor({ inv, format, fields, onChange, saving, onSave, referenceOptions, onValidate, validating }: {
  inv: DgiiPreviewInvoice;
  format: DgiiFormat;
  fields: Record<string, unknown>;
  onChange: (key: string, value: unknown) => void;
  saving: boolean;
  onSave: () => void;
  referenceOptions: DgiiReferenceOptions;
  onValidate?: () => void;
  validating?: boolean;
}) {
  const set = (k: string) => (v: string) => onChange(k, v === "__none" ? "" : v);
  const val = (k: string) => (fields[k] as string) ?? "";
  const numVal = (k: string) => fields[k] != null ? String(fields[k]) : "";

  return (
    <div className="px-4 py-3 space-y-3" role="presentation" onClick={e => e.stopPropagation()}>
      {/* Validation issues */}
      {(inv.validation_errors.length > 0 || inv.validation_warnings.length > 0) && (
        <div className="flex flex-wrap gap-2 text-[10px]">
          {inv.validation_errors.map((e, i) => (
            <span key={`e-${i}`} className="flex items-center gap-1 text-red-600 bg-red-50 rounded px-1.5 py-0.5">
              <XCircle className="size-2.5" />{e}
            </span>
          ))}
          {inv.validation_warnings.map((w, i) => (
            <span key={`w-${i}`} className="flex items-center gap-1 text-amber-600 bg-amber-50 rounded px-1.5 py-0.5">
              <AlertTriangle className="size-2.5" />{w}
            </span>
          ))}
        </div>
      )}

      {/* Core fields */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
        <FieldInput label="RNC/Cédula" value={val("vendor_tax_id")} onChange={set("vendor_tax_id")} placeholder="130000001" />
        <FieldInput label="NCF" value={val("invoice_number")} onChange={set("invoice_number")} placeholder="E310000000001" />
        <FieldInput label="NCF Modificado" value={val("ncf_modified")} onChange={set("ncf_modified")} placeholder="E340000000001" />
        {format === "dgii_606" && (
          <FieldSelect
            label="Tipo B/S"
            value={val("goods_services_type")}
            onChange={set("goods_services_type")}
            options={referenceOptions.goodsServicesTypes}
          />
        )}
        {format === "dgii_607" && (
          <FieldSelect
            label="Tipo Ingreso"
            value={val("tipo_ingreso")}
            onChange={set("tipo_ingreso")}
            options={referenceOptions.incomeTypes}
          />
        )}
        {format === "dgii_608" && (
          <FieldSelect
            label="Tipo Anulación"
            value={val("cancellation_type")}
            onChange={set("cancellation_type")}
            options={referenceOptions.cancellationTypes}
          />
        )}
        <FieldInput label="Fecha Pago" value={val("payment_date")} onChange={set("payment_date")} type="date" />
        {format !== "dgii_608" && (
          <FieldSelect
            label="Forma de Pago"
            value={val("payment_method")}
            onChange={set("payment_method")}
            options={referenceOptions.paymentMethods}
          />
        )}
      </div>

      {/* ITBIS & Retenciones (only for 606/607) */}
      {format !== "dgii_608" && (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
          <FieldInput label="ITBIS Retenido" value={numVal("itbis_retenido")} onChange={set("itbis_retenido")} type="number" />
          <FieldInput label="ITBIS Proporcionalidad" value={numVal("itbis_proporcionalidad")} onChange={set("itbis_proporcionalidad")} type="number" />
          <FieldInput label="ITBIS al Costo" value={numVal("itbis_llevado_costo")} onChange={set("itbis_llevado_costo")} type="number" />
          <FieldInput label="ITBIS Percibido" value={numVal("itbis_percibido")} onChange={set("itbis_percibido")} type="number" />
          <FieldSelect
            label="Tipo Ret. ISR"
            value={val("isr_retention_type")}
            onChange={set("isr_retention_type")}
            options={referenceOptions.isrRetentionTypes}
          />
          <FieldInput label="Monto Ret. Renta" value={numVal("isr_retention_amount")} onChange={set("isr_retention_amount")} type="number" />
        </div>
      )}

      {/* ISR + Other taxes (only for 606/607) */}
      {format !== "dgii_608" && (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
          <FieldInput label="ISR Percibido" value={numVal("isr_percibido")} onChange={set("isr_percibido")} type="number" />
          <FieldInput label="ISC" value={numVal("isc_amount")} onChange={set("isc_amount")} type="number" />
          <FieldInput label="Otros Impuestos" value={numVal("other_taxes")} onChange={set("other_taxes")} type="number" />
          <FieldInput label="Propina Legal" value={numVal("legal_tip")} onChange={set("legal_tip")} type="number" />
          {format === "dgii_607" && (
            <FieldInput label="Ret. Renta Terceros" value={numVal("retencion_renta_terceros")} onChange={set("retencion_renta_terceros")} type="number" />
          )}
        </div>
      )}

      {/* Save & Validate */}
      <div className="flex justify-between items-center pt-1">
        <div>
          {onValidate && (
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="h-7 text-xs gap-1.5 border-primary text-primary hover:bg-primary/5"
              onClick={onValidate}
              disabled={validating || saving}
            >
              {validating ? (
                <Loader2 className="size-3 animate-spin" />
              ) : (
                <Globe className="size-3" />
              )}
              {validating ? "Validando..." : "Validar ante DGII"}
            </Button>
          )}
        </div>
        <Button size="sm" className="h-7 text-xs gap-1.5" onClick={onSave} disabled={saving || validating}>
          {saving ? <Loader2 className="size-3 animate-spin" /> : <Save className="size-3" />}
          {saving ? "Guardando..." : "Guardar cambios"}
        </Button>
      </div>
    </div>
  );
}

// ── Component ──────────────────────────────────────────────────────────────

export function DgiiPage() {
  const { options: referenceOptions, loading: referenceLoading } = useDgiiReferenceOptions();
  const [selectedFormat, setSelectedFormat] = useState<DgiiFormat>("dgii_606");
  const [period, setPeriod] = useState(currentPeriod());
  const [categories, setCategories] = useState<string[]>([]);
  const [selectedCategories, setSelectedCategories] = useState<string[]>([]);
  const [selectedGoodsTypes, setSelectedGoodsTypes] = useState<string[]>([]);
  const [selectedSources, setSelectedSources] = useState<string[]>([]);
  const [vendorSearch, setVendorSearch] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [includeNoNcf, setIncludeNoNcf] = useState(false);
  const [preview, setPreview] = useState<DgiiPreviewResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filterSearch, setFilterSearch] = useState("");
  const [autoFixes, setAutoFixes] = useState<string[]>([]);
  const [confirmFix, setConfirmFix] = useState<string | null>(null);
  const [fixing, setFixing] = useState(false);
  const [outputFormat, setOutputFormat] = useState<"dgii_txt" | "xls" | "csv">("dgii_txt");
  const [editInvoice, setEditInvoice] = useState<DgiiPreviewInvoice | null>(null);
  const [editingFields, setEditingFields] = useState<Record<string, unknown>>({});
  const [savingField, setSavingField] = useState(false);
  const [spreadsheetOpen, setSpreadsheetOpen] = useState(false);
  const [errorReviewOpen, setErrorReviewOpen] = useState(false);
  const [validatingIds, setValidatingIds] = useState<Record<string, boolean>>({});

  // Submission tracking
  const [pendingSummary, setPendingSummary] = useState<DgiiPendingSummary | null>(null);
  const [showSubmissionDialog, setShowSubmissionDialog] = useState(false);
  const [submittingIds, setSubmittingIds] = useState<string[]>([]);
  const [submittingPeriod, setSubmittingPeriod] = useState("");
  const [submissionSaving, setSubmissionSaving] = useState(false);
  const [submissionMessage, setSubmissionMessage] = useState<string | null>(null);

  // Auto-generate
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [autoGenPhase, setAutoGenPhase] = useState("");
  const [autoGenResult, setAutoGenResult] = useState<DgiiAutoGenerateResult | null>(null);
  const [autoGenInvoiceIds, setAutoGenInvoiceIds] = useState<string[] | undefined>(undefined);

  // Exclude reported toggle
  const [excludeReported, setExcludeReported] = useState(true);

  const filteredPreview = preview?.preview_invoices.filter(inv => {
    if (!filterSearch) return true;
    const q = filterSearch.toLowerCase();
    return inv.vendor_name.toLowerCase().includes(q) || inv.invoice_number.toLowerCase().includes(q) || inv.vendor_tax_id.includes(q);
  }) ?? [];

  useEffect(() => {
    getDgiiCategories().then(setCategories).catch(() => { });
    getDgiiPendingSummary().then(setPendingSummary).catch(() => {});
  }, []);

  // Refresh pending summary periodically
  useEffect(() => {
    getDgiiPendingSummary().then(setPendingSummary).catch(() => {});
  }, [preview]);

  const buildFilters = useCallback((extraFixes?: string[], overrideIds?: string[]) => {
    const fixes = extraFixes ?? autoFixes;
    const hasCustomDates = dateFrom || dateTo;
    const ids = overrideIds ?? autoGenInvoiceIds;
    return {
      format: selectedFormat,
      period: ids ? undefined : (hasCustomDates ? undefined : period),
      date_from: ids ? undefined : (dateFrom || undefined),
      date_to: ids ? undefined : (dateTo || undefined),
      categories: selectedCategories.length ? selectedCategories : undefined,
      goods_types: selectedGoodsTypes.length ? selectedGoodsTypes : undefined,
      vendor_search: vendorSearch || undefined,
      source_types: selectedSources.length ? selectedSources : undefined,
      include_no_ncf: includeNoNcf,
      exclude_reported: false,
      invoice_ids: ids,
      auto_fixes: fixes.length ? fixes : undefined,
      output_format: outputFormat,
    };
  }, [selectedFormat, period, dateFrom, dateTo, selectedCategories, selectedGoodsTypes, vendorSearch, selectedSources, includeNoNcf, excludeReported, autoFixes, outputFormat, autoGenInvoiceIds]);

  const runPreview = useCallback(async (extraFixes?: string[], overrideIds?: string[]) => {
    setLoading(true);
    setError(null);
    try {
      const result = await previewDgiiExport(buildFilters(extraFixes, overrideIds));
      setPreview(result);
      if (extraFixes) setAutoFixes(extraFixes);
    } catch (e: any) {
      setError(e.message || "Error al previsualizar");
    } finally {
      setLoading(false);
    }
  }, [buildFilters]);

  const runPreviewRef = useRef(runPreview);

  useEffect(() => {
    runPreviewRef.current = runPreview;
  }, [runPreview]);

  const handleValidateInvoice = useCallback(async (invoiceId: string) => {
    setValidatingIds(prev => ({ ...prev, [invoiceId]: true }));
    try {
      const res = await validateInvoiceDgii(invoiceId);
      if (res.validation.status === "accepted") {
        toast.success(`Factura validada correctamente ante la DGII. NCF: ${res.validation.encf}`);
      } else if (res.validation.status === "rejected") {
        toast.error(`Factura rechazada por la DGII: ${res.validation.description || "Comprobante inválido"}`);
      } else {
        toast.warning(`Advertencia de validación: ${res.validation.description || "Error de validación"}`);
      }
      await runPreview();
    } catch (err: any) {
      toast.error(`Error al validar factura: ${err.message || "Error desconocido"}`);
    } finally {
      setValidatingIds(prev => ({ ...prev, [invoiceId]: false }));
    }
  }, [runPreview]);

  const [bulkValidating, setBulkValidating] = useState(false);

  const handleBulkValidate = useCallback(async () => {
    const targetInvoices = filteredPreview.length > 0 ? filteredPreview : (preview?.preview_invoices || []);
    if (targetInvoices.length === 0) return;

    setBulkValidating(true);
    const invoiceIds = targetInvoices.map(inv => inv.id);

    // Set all to validating state
    const initialValidating: Record<string, boolean> = {};
    invoiceIds.forEach(id => { initialValidating[id] = true; });
    setValidatingIds(initialValidating);

    toast.info(`Iniciando validación en masa de ${invoiceIds.length} facturas ante la DGII...`);
    try {
      const res = await dgiiVerifyNcf({ invoice_ids: invoiceIds });
      toast.success(`Validación masiva finalizada: ${res.found} encontradas, ${res.not_found} no encontradas/con error.`);
      await runPreview();
    } catch (err: any) {
      toast.error(`Error en validación masiva: ${err.message || "Error desconocido"}`);
    } finally {
      setValidatingIds({});
      setBulkValidating(false);
    }
  }, [preview, filteredPreview, runPreview]);

  useEffect(() => {
    setAutoGenInvoiceIds(undefined);
    setAutoGenResult(null);
    if (selectedFormat) {
      void runPreviewRef.current();
    }
  }, [selectedFormat, period, dateFrom, dateTo]);

  async function handleDownload() {
    setDownloading(true);
    setError(null);
    try {
      const { blob, filename } = await downloadDgiiExport(buildFilters());
      triggerBlobDownload(blob, filename);
      // After successful download, offer to mark as submitted
      const fmt = selectedFormat.replace("dgii_", "");
      const p = dateFrom || dateTo ? (dateFrom?.slice(0, 7).replace("-", "") ?? period) : period;
      setSubmittingPeriod(p);
      if (preview?.preview_invoices?.length) {
        setSubmittingIds(
          preview.preview_invoices.reduce<string[]>((acc, inv) => {
            if (inv.reporting_state !== "blocked_confirmed_ncf") {
              acc.push(inv.id);
            }
            return acc;
          }, []),
        );
      }
      setShowSubmissionDialog(true);
    } catch (e: any) {
      setError(e.message || "Error al descargar");
    } finally {
      setDownloading(false);
    }
  }

  async function handleAutoGenerate() {
    setAutoGenerating(true);
    setAutoGenResult(null);
    setError(null);

    const phases = [
      "Escaneando facturas del período...",
      "Buscando pendientes de meses anteriores...",
      "Completando campos automáticamente...",
      "Verificando montos e ITBIS...",
      "Preparando reporte...",
    ];

    // Animated phase display (just for show — runs in parallel with API)
    let phaseIdx = 0;
    const phaseInterval = setInterval(() => {
      if (phaseIdx < phases.length) {
        setAutoGenPhase(phases[phaseIdx]);
        phaseIdx++;
      }
    }, 600);

    try {
      const fmt = selectedFormat.replace("dgii_", "");
      const result = await autoGenerateDgiiReport(fmt, dateFrom || dateTo ? undefined : period);
      clearInterval(phaseInterval);
      setAutoGenPhase("");

      if (result.status === "empty") {
        setAutoGenResult(result);
        setPreview(null);
        setAutoGenerating(false);
        return;
      }

      setAutoGenResult(result);

      // Extract invoice IDs from auto-generate result and use them for preview
      // so past-due invoices (from previous months) are included
      const ids = result.invoices?.map(inv => inv.id) || [];
      setAutoGenInvoiceIds(ids);
      await runPreview(["assign_goods_type", "recalculate_itbis", "deduplicate"], ids);
    } catch (e: any) {
      clearInterval(phaseInterval);
      setAutoGenPhase("");
      setError(e.message || "Error al auto-generar reporte");
    } finally {
      setAutoGenerating(false);
    }
  }

  async function handleMarkAsSubmitted(status: "confirmed" | "pending_confirm" | "pending_upload") {
    if (!submittingIds.length) return;
    setSubmissionSaving(true);
    try {
      const fmt = selectedFormat.replace("dgii_", "");
      await createDgiiSubmission({
        format: fmt,
        period: submittingPeriod,
        invoice_ids: submittingIds,
        status,
      });
      setShowSubmissionDialog(false);
      // Re-run preview and refresh pending summary
      await runPreview();
      const summary = await getDgiiPendingSummary();
      setPendingSummary(summary);

      if (status === "pending_upload") {
        setSubmissionMessage("Envío pendiente registrado. Ve a la sección de Envíos para marcarlo como subido cuando hayas cargado el reporte en la DGII.");
      } else if (status === "pending_confirm") {
        setSubmissionMessage("Envío creado. Ve a la sección de Envíos para reportar los resultados por factura.");
      } else {
        setSubmissionMessage(`${submittingIds.length} factura(s) registrada(s) como enviadas.`);
      }
    } catch (e: any) {
      setError(e.message || "Error al registrar envío");
    } finally {
      setSubmissionSaving(false);
    }
  }

  async function handleConfirmFix() {
    if (!confirmFix) return;
    setFixing(true);
    setConfirmFix(null);
    const newFixes = [...new Set([...autoFixes, confirmFix])];
    await runPreview(newFixes);
    setFixing(false);
  }

  const FIX_CONFIG: Record<string, { title: string; desc: string; icon: ReactNode; warning: string }> = {
    deduplicate: {
      title: "Eliminar NCFs duplicados",
      icon: <CopyX className="size-3.5" />,
      desc: "El sistema identificará facturas con el mismo NCF y conservará solo la más completa. Las demás se excluirán de esta exportación.",
      warning: "Los duplicados no se eliminarán de la base de datos, solo se excluirán de este reporte.",
    },
    recalculate_itbis: {
      title: "Recalcular ITBIS",
      icon: <Percent className="size-3.5" />,
      desc: "El sistema recalculará el ITBIS a la tasa correcta (18%/16%/0%) para cada factura donde no coincida.",
      warning: "Esta acción MODIFICA la base de datos. Los valores de ITBIS se actualizarán permanentemente.",
    },
    assign_goods_type: {
      title: "Asignar tipo B/S automáticamente",
      icon: <WandSparkles className="size-3.5" />,
      desc: "El sistema asignará el tipo de bien/servicio (01-11) basado en la categoría de cada factura.",
      warning: "Esta acción MODIFICA la base de datos. Los tipos B/S se actualizarán permanentemente.",
    },
  }

  const fmt = REPORTS.find(r => r.id === selectedFormat)!;
  const visibleCount = preview?.total_visible_invoices ?? preview?.total_invoices ?? 0;
  const reportableCount = preview?.reportable_invoices ?? preview?.total_invoices ?? 0;
  const blockedConfirmedCount = preview?.blocked_confirmed_ncf ?? 0;
  const canExport = !!preview && reportableCount > 0 && !loading && preview.can_export !== false;
  const completePct = preview ? Math.round((preview.complete / Math.max(preview.total_invoices, 1)) * 100) : 0;

  return (
    <div className="flex flex-col gap-4">
      {/* Header */}
      <Card>
        <CardHeader className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <CardTitle className="flex items-center gap-2 text-lg">
              <ShieldCheck className="size-5 text-primary" />
              Reportes DGII
            </CardTitle>
            <p className="text-xs text-muted-foreground">
              Selecciona el formulario, el período y los filtros. Previsualiza antes de descargar.
            </p>
          </div>
          <div className="flex items-center gap-2">
            {dateFrom || dateTo ? (
              <div className="flex items-center gap-2 rounded-md border px-3 py-1.5 bg-card min-w-[12rem] justify-center">
                <Calendar className="size-3.5 text-muted-foreground" />
                <span className="text-xs font-medium">{dateFrom || "—"} → {dateTo || "—"}</span>
              </div>
            ) : (
              <>
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0" onClick={() => setPeriod(prevPeriod(period))}>
                  <ChevronLeft className="size-4" />
                </Button>
                <div className="flex items-center gap-2 rounded-md border px-3 py-1.5 bg-card min-w-[10rem] justify-center">
                  <Calendar className="size-3.5 text-muted-foreground" />
                  <span className="text-sm font-medium">{periodLabel(period)}</span>
                </div>
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0" onClick={() => setPeriod(nextPeriod(period))}>
                  <ChevronRight className="size-4" />
                </Button>
              </>
            )}
            <div className="relative">
              <Button
                size="sm"
                className="h-8 text-xs gap-1.5 shadow-sm"
                onClick={handleAutoGenerate}
                disabled={autoGenerating}
              >
                {autoGenerating ? (
                  <><Loader2 className="size-3.5 animate-spin" />{autoGenPhase || "Generando..."}</>
                ) : (
                  <><WandSparkles className="size-3.5" /> Auto-generar</>
                )}
              </Button>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Auto-generate result banner */}
      {autoGenResult && (
        <Card className={cn(
          "border-l-4",
          autoGenResult.status === "empty"
            ? "border-l-slate-400 bg-slate-50/60"
            : autoGenResult.summary.issues > 0
              ? "border-l-amber-500 bg-amber-50/60"
              : "border-l-emerald-500 bg-emerald-50/60"
        )}>
          <CardContent className="py-3 px-4">
            <div className="flex items-start justify-between gap-3">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 text-sm font-semibold mb-0.5">
                  {autoGenResult.status === "empty" ? (
                    <><Inbox className="size-3.5 inline-block mr-1" /> Sin facturas pendientes</>
                  ) : (
                    <><WandSparkles className="size-3.5 inline-block mr-1 text-indigo-500" />{autoGenResult.summary.message}</>
                  )}
                </div>
                {autoGenResult.status === "success" && (
                  <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground mt-0.5">
                    <span>{autoGenResult.summary.new_this_period} del período</span>
                    {autoGenResult.summary.from_previous_periods > 0 && (
                      <span className="text-amber-600 font-medium flex items-center gap-1">
                        <Clock className="size-3" /> {autoGenResult.summary.from_previous_periods} de meses anteriores
                      </span>
                    )}
                    {autoGenResult.summary.from_errors > 0 && (
                      <span className="text-red-600 font-medium flex items-center gap-1">
                        <AlertTriangle className="size-3" /> {autoGenResult.summary.from_errors} con error previo
                      </span>
                    )}
                    {Object.entries(autoGenResult.summary.fixes_applied).map(([key, val]) => (
                      <span key={key} className="text-emerald-600 flex items-center gap-1">
                        <PencilLine className="size-3" /> {key === "goods_type_fixed" ? `${val} tipo(s) B/S` :
                           key === "itbis_fixed" ? `${val} ITBIS` :
                           key === "duplicates_removed" ? `${val} duplicado(s)` :
                           `${key}: ${val}`}
                      </span>
                    ))}
                    <span className={autoGenResult.summary.issues > 0 ? "text-amber-600" : "text-emerald-600"}>
                      {autoGenResult.summary.complete} OK · {autoGenResult.summary.issues} con issues
                    </span>
                  </div>
                )}
              </div>
              <Button
                variant="ghost"
                size="sm"
                className="h-6 w-6 p-0 shrink-0"
                onClick={() => setAutoGenResult(null)}
              >
                <XCircle className="size-3.5 text-muted-foreground" />
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Pending Summary Banner */}
      {pendingSummary && pendingSummary.total_pending > 0 && (
        <Card className={cn(
          "border-l-4",
          pendingSummary.past_due_count > 0 ? "border-l-amber-500 bg-amber-50/60" : "border-l-blue-500 bg-blue-50/60"
        )}>
          <CardContent className="py-3 px-4">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
              <div className="flex flex-wrap items-center gap-x-4 gap-y-1">
                <span className="flex items-center gap-1.5 text-sm font-semibold text-foreground">
                  <FileText className="size-4" />
                  {pendingSummary.total_pending} factura(s) pendientes
                </span>
                {pendingSummary.past_due_count > 0 && (
                  <span className="flex items-center gap-1 text-xs text-amber-700 font-medium">
                    <AlertTriangle className="size-3.5" />
                    {pendingSummary.past_due_count} de períodos anteriores
                  </span>
                )}
                <span className="flex items-center gap-1 text-xs text-muted-foreground">
                  <Calendar className="size-3.5" />
                  Próximo vencimiento: {new Date(pendingSummary.next_deadline + "T12:00:00").toLocaleDateString("es-DO", { day: "numeric", month: "long", year: "numeric" })}
                </span>
              </div>
              <div className="flex items-center gap-3 text-xs flex-wrap">
                {Object.entries(pendingSummary.by_format).map(([fmt, count]) => (
                  <span key={fmt} className={cn(
                    "inline-flex items-center gap-1 rounded-full px-2 py-0.5 font-medium",
                    count > 0 ? "bg-primary/10 text-primary" : "text-muted-foreground"
                  )}>
                    {fmt === "606" ? "Compras" : fmt === "607" ? "Ventas" : "Anulac."}
                    <span className="font-bold">{count}</span>
                  </span>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Report Selector */}
      <div className="grid grid-cols-3 gap-3">
        {REPORTS.map(r => (
          <button
            key={r.id}
            type="button"
            onClick={() => setSelectedFormat(r.id)}
            className={cn(
              "flex flex-col gap-1.5 rounded-xl border-2 p-4 text-left transition-all",
              selectedFormat === r.id ? "border-primary bg-primary/5 ring-2 ring-primary/20" : "border-border bg-card hover:border-primary/30"
            )}
          >
            <span className={cn("inline-flex w-fit rounded-md border px-2 py-0.5 text-[10px] font-bold tracking-wider uppercase", r.color)}>
              {r.label}
            </span>
            <p className="text-xs text-muted-foreground leading-tight">{r.desc}</p>
          </button>
        ))}
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        {/* Filters Panel */}
        <Card className="lg:col-span-1">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-sm">
              <Filter className="size-3.5 text-muted-foreground" />
              Filtros de selección
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-4 pt-0">
            {/* Vendor search */}
            <div className="flex flex-col gap-1.5">
              <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Proveedor / RNC</Label>
              <Input
                placeholder="Buscar proveedor o RNC..."
                value={vendorSearch}
                onChange={e => setVendorSearch(e.target.value)}
                className="h-8 text-xs"
              />
            </div>

            {/* Categories */}
            {categories.length > 0 && (
              <div className="flex flex-col gap-1.5">
                <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Categorías ({selectedCategories.length} seleccionadas)
                </Label>
                <div className="flex flex-wrap gap-1.5 max-h-32 overflow-y-auto rounded-md border p-2">
                  {categories.map(cat => (
                    <button
                      key={cat}
                      type="button"
                      onClick={() => setSelectedCategories(prev =>
                        prev.includes(cat) ? prev.filter(c => c !== cat) : [...prev, cat]
                      )}
                      className={cn(
                        "rounded px-2 py-0.5 text-[10px] font-medium transition-colors",
                        selectedCategories.includes(cat)
                          ? "bg-primary text-primary-foreground"
                          : "bg-muted text-muted-foreground hover:bg-muted/80"
                      )}
                    >
                      {cat}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Goods Types (only for 606) */}
            {selectedFormat === "dgii_606" && (
              <div className="flex flex-col gap-1.5">
                <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Tipo B/S ({selectedGoodsTypes.length} seleccionados)
                </Label>
                <div className="flex flex-col gap-1 max-h-32 overflow-y-auto rounded-md border p-2">
                  {referenceOptions.goodsServicesTypes.length > 0 ? (
                    referenceOptions.goodsServicesTypes.map((goodsType) => (
                      <label key={goodsType.value} className="flex items-center gap-2 cursor-pointer rounded px-1 py-0.5 hover:bg-muted text-[10px]">
                        <Checkbox
                          checked={selectedGoodsTypes.includes(goodsType.value)}
                          onCheckedChange={() => setSelectedGoodsTypes((prev) =>
                            prev.includes(goodsType.value)
                              ? prev.filter((value) => value !== goodsType.value)
                              : [...prev, goodsType.value]
                          )}
                          className="size-3"
                        />
                        {goodsType.label}
                      </label>
                    ))
                  ) : (
                    <p className="px-1 py-1 text-[10px] text-muted-foreground">
                      {referenceLoading.goodsServicesTypes ? "Cargando catálogo..." : "Catálogo no disponible"}
                    </p>
                  )}
                </div>
              </div>
            )}

            {/* Source types */}
            <div className="flex flex-col gap-1.5">
              <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                Origen de la factura
              </Label>
              <div className="flex flex-wrap gap-1.5">
                {SOURCE_TYPES.map(st => (
                  <button
                    key={st.value}
                    type="button"
                    onClick={() => setSelectedSources(prev =>
                      prev.includes(st.value) ? prev.filter(s => s !== st.value) : [...prev, st.value]
                    )}
                    className={cn(
                      "rounded px-2 py-0.5 text-[10px] font-medium transition-colors border",
                      selectedSources.includes(st.value)
                        ? "bg-primary text-primary-foreground border-primary"
                        : "border-border text-muted-foreground hover:border-primary/40"
                    )}
                  >
                    {st.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Custom date range */}
            <div className="flex flex-col gap-1.5">
              <Label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Rango de fechas personalizado</Label>
              <div className="flex gap-2 items-center">
                <DgiiDateInput
                  value={dateFrom}
                  onChange={setDateFrom}
                  placeholder="DD-MM-YYYY"
                  className="flex-1"
                />
                <span className="text-[10px] text-muted-foreground shrink-0">→</span>
                <DgiiDateInput
                  value={dateTo}
                  onChange={setDateTo}
                  placeholder="DD-MM-YYYY"
                  className="flex-1"
                />
              </div>
            </div>

            {/* Include no-NCF */}
            <label htmlFor="include-no-ncf" className="flex items-center gap-2 cursor-pointer text-xs">
              <Checkbox id="include-no-ncf" checked={includeNoNcf} onCheckedChange={v => setIncludeNoNcf(!!v)} className="size-3.5" />
              <span className="text-muted-foreground">Incluir facturas sin NCF</span>
            </label>

            {/* Exclude reported toggle */}
            <label htmlFor="exclude-reported" className="flex items-center gap-2 cursor-pointer text-xs">
              <Checkbox id="exclude-reported" checked={excludeReported} onCheckedChange={v => setExcludeReported(!!v)} className="size-3.5" />
              <span className="text-muted-foreground">Ocultar facturas ya enviadas</span>
            </label>

            {/* Actions */}
            <div className="flex flex-col gap-2 pt-1">
              <div className="flex gap-2">
                <Button variant="outline" size="sm" className="flex-1 text-xs" onClick={() => { setAutoGenInvoiceIds(undefined); setAutoGenResult(null); runPreview(); }} disabled={loading || fixing}>
                  <Eye className="size-3 mr-1" />
                  {loading ? "Calculando..." : "Previsualizar"}
                </Button>
                <Button
                  size="sm"
                  className="flex-1 text-xs"
                  disabled={!canExport || downloading}
                  onClick={handleDownload}
                >
                  {downloading ? <Loader2 className="size-3 mr-1 animate-spin" /> : <Download className="size-3 mr-1" />}
                  {downloading ? "Descargando..." : "Descargar"}
                </Button>
              </div>
              {preview && preview.preview_invoices && preview.preview_invoices.length > 0 && (
                <Button
                  variant="secondary"
                  size="sm"
                  className="w-full text-xs gap-1.5"
                  disabled={bulkValidating || loading}
                  onClick={handleBulkValidate}
                >
                  {bulkValidating ? (
                    <Loader2 className="size-3 animate-spin text-primary" />
                  ) : (
                    <Globe className="size-3" />
                  )}
                  {bulkValidating ? "Validando en masa..." : `Validar ${filteredPreview.length} facturas ante DGII`}
                </Button>
              )}
            </div>

            {/* Reset filters */}
            <Button
              variant="ghost"
              size="sm"
              className="w-full text-[10px] text-muted-foreground"
              onClick={() => {
                setSelectedCategories([]);
                setSelectedGoodsTypes([]);
                setSelectedSources([]);
                setVendorSearch("");
                setIncludeNoNcf(false);
                setDateFrom("");
                setDateTo("");
                setAutoFixes([]);
                setOutputFormat("dgii_txt");
                setExcludeReported(true);
                setAutoGenInvoiceIds(undefined);
                setAutoGenResult(null);
              }}
            >
              <RefreshCw className="size-3 mr-1" />
              Limpiar filtros
            </Button>

            {error && (
              <p className="rounded-md bg-destructive/10 px-2 py-1.5 text-[10px] text-destructive">{error}</p>
            )}
          </CardContent>
        </Card>

        {/* Preview + Stats */}
        <div className="flex flex-col gap-4 lg:col-span-2">
          {/* Stats bar */}
          {preview && (
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              <Card>
                <CardHeader className="pb-1 pt-3 px-4">
                  <CardDescription className="text-[10px] uppercase tracking-wider flex gap-1 items-center">
                    <FileText className="size-3" /> Facturas
                  </CardDescription>
                  <CardTitle className="text-xl">{preview.total_invoices}</CardTitle>
                </CardHeader>
                <CardFooter className="pb-3 pt-0 px-4">
                  <div className="w-full h-1 rounded-full bg-muted overflow-hidden">
                    <div className="h-full rounded-full bg-primary transition-all" style={{ width: `${completePct}%` }} />
                  </div>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader className="pb-1 pt-3 px-4">
                  <CardDescription className="text-[10px] uppercase tracking-wider flex gap-1 items-center">
                    <CheckCircle2 className="size-3 text-emerald-500" /> Completas
                  </CardDescription>
                  <CardTitle className="text-xl text-emerald-600">{preview.complete}</CardTitle>
                </CardHeader>
                <CardFooter className="pb-3 pt-0 px-4">
                  <span className="text-[10px] text-muted-foreground">{completePct}% listas</span>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader className="pb-1 pt-3 px-4">
                  <CardDescription className="text-[10px] uppercase tracking-wider flex gap-1 items-center">
                    <Banknote className="size-3" /> Monto Total
                  </CardDescription>
                  <CardTitle className="text-base leading-tight font-semibold">{fmtCurrency(preview.total_amount)}</CardTitle>
                </CardHeader>
                <CardFooter className="pb-3 pt-0 px-4">
                  <span className="text-[10px] text-muted-foreground">Antes de ITBIS</span>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader className="pb-1 pt-3 px-4">
                  <CardDescription className="text-[10px] uppercase tracking-wider flex gap-1 items-center">
                    <Percent className="size-3" /> ITBIS Total
                  </CardDescription>
                  <CardTitle className="text-base leading-tight font-semibold">{fmtCurrency(preview.total_tax)}</CardTitle>
                </CardHeader>
                <CardFooter className="pb-3 pt-0 px-4">
                  <span className="text-[10px] text-muted-foreground">Impuesto</span>
                </CardFooter>
              </Card>
            </div>
          )}

          {/* Validation banners */}
          {preview && !preview.can_export && (
            <Card className="border-red-300 bg-red-50/60">
              <CardContent className="py-3 px-4">
                <p className="text-xs font-semibold text-red-700 mb-2 flex items-center gap-1.5">
                  <XCircle className="size-3.5" /> Errores bloqueantes — corrige antes de exportar
                </p>
                <div className="flex flex-wrap gap-x-4 gap-y-1.5 text-[11px] text-red-600">
                  {preview.duplicates?.map(d => (
                    <span key={d.ncf} className="flex items-center gap-1"><CopyX className="size-3" />NCF duplicado: {d.ncf} ({d.count}x)</span>
                  ))}
                  {preview.missing_ncf > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />{preview.missing_ncf} sin NCF</span>}
                  {preview.missing_rnc > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />{preview.missing_rnc} sin RNC</span>}
                  {preview.invalid_ncf > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />{preview.invalid_ncf} NCF inválidos</span>}
                  {preview.invalid_rnc > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />{preview.invalid_rnc} RNC inválidos</span>}
                  {preview.zero_amount > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />{preview.zero_amount} con monto en cero</span>}
                  {preview.missing_goods_type > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />{preview.missing_goods_type} sin Tipo B/S</span>}
                  {preview.missing_payment_method > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />{preview.missing_payment_method} sin forma de pago</span>}
                  {preview.invalid_payment_method > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />{preview.invalid_payment_method} forma(s) de pago inválidas</span>}
                  {preview.missing_report_rnc > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />Organización sin RNC/Cédula</span>}
                  {preview.invalid_report_rnc > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />RNC/Cédula de organización inválido</span>}
                  {preview.invalid_period > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />Período inválido</span>}
                  {preview.record_limit_exceeded > 0 && <span className="flex items-center gap-1"><XCircle className="size-3" />Límite de registros excedido</span>}
                  {preview.report_errors?.map((message) => (
                    <span key={message} className="basis-full text-[10px] text-red-700">{message}</span>
                  ))}
                </div>
                {/* Fix buttons */}
                <div className="flex flex-wrap gap-2 mt-3 pt-2 border-t border-red-200">
                  {preview.duplicates && preview.duplicates.length > 0 && !autoFixes.includes("deduplicate") && (
                    <Button size="sm" variant="outline" className="h-7 text-[10px] border-red-300 text-red-700 hover:bg-red-100" onClick={() => setConfirmFix("deduplicate")}>
                      <WandSparkles className="size-3 mr-1" />Corregir NCFs
                    </Button>
                  )}
                  {preview.missing_goods_type > 0 && selectedFormat === "dgii_606" && !autoFixes.includes("assign_goods_type") && (
                    <Button size="sm" variant="outline" className="h-7 text-[10px] border-red-300 text-red-700 hover:bg-red-100" onClick={() => setConfirmFix("assign_goods_type")}>
                      <WandSparkles className="size-3 mr-1" />Asignar tipo B/S
                    </Button>
                  )}
                  <Button
                    size="sm"
                    variant="default"
                    className="h-7 text-[10px] bg-red-600 hover:bg-red-700 text-white gap-1"
                    onClick={() => setErrorReviewOpen(true)}
                  >
                    <AlertTriangle className="size-3" />
                    Revisar facturas con errores
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
          {preview && (preview.has_itbis_errors || preview.total_warnings > 0) && (
            <Card className="border-amber-200 bg-amber-50/50">
              <CardContent className="py-3 px-4">
                <p className="text-xs font-semibold text-amber-700 mb-2 flex items-center gap-1.5">
                  <AlertTriangle className="size-3.5" /> Advertencias ({preview.total_warnings}) — no bloquean la exportación
                </p>
                <div className="flex flex-wrap gap-x-4 gap-y-1.5 text-[11px] text-amber-600">
                  {preview.has_itbis_errors && <span className="flex items-center gap-1"><Percent className="size-3" />ITBIS no coincide con tasa esperada (18%/16%/0%) en algunas facturas</span>}
                </div>
                {preview.has_itbis_errors && !autoFixes.includes("recalculate_itbis") && (
                  <div className="flex flex-wrap gap-2 mt-3 pt-2 border-t border-amber-200">
                    <Button size="sm" variant="outline" className="h-7 text-[10px] border-amber-300 text-amber-700 hover:bg-amber-100" onClick={() => setConfirmFix("recalculate_itbis")}>
                      <WandSparkles className="size-3 mr-1" />Recalcular ITBIS
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
          )}
          {/* Fixes applied feedback */}
          {preview?.fixes_applied && Object.keys(preview.fixes_applied).length > 0 && (
            <Card className="border-emerald-200 bg-emerald-50/50">
              <CardContent className="py-2 px-4 flex flex-wrap items-center gap-x-4 gap-y-1 text-[11px] text-emerald-700">
                <CheckCircle2 className="size-3.5" />
                {preview.fixes_applied.duplicates_removed && (
                  <span>{preview.fixes_applied.duplicates_removed} duplicado(s) excluido(s)</span>
                )}
                {preview.fixes_applied.itbis_fixed && (
                  <span>{preview.fixes_applied.itbis_fixed} ITBIS recalculado(s)</span>
                )}
                {preview.fixes_applied.goods_type_fixed && (
                  <span>{preview.fixes_applied.goods_type_fixed} tipo(s) B/S asignado(s)</span>
                )}
              </CardContent>
            </Card>
          )}

          {/* Preview Table */}
          <Card>
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2 text-sm">
                    <Eye className="size-3.5 text-muted-foreground" />
                    Vista previa {preview ? `(${visibleCount} facturas, mostrando primeras ${Math.min(20, visibleCount)})` : ""}
                  </CardTitle>
                {preview && (
                  <div className="flex items-center gap-2">
                    {/* Open spreadsheet dialog */}
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-7 text-[10px] gap-1.5"
                      onClick={() => setSpreadsheetOpen(true)}
                    >
                      <Sheet className="size-3" />
                      Vista Plantilla
                    </Button>
                    <div className="relative">
                      <Search className="pointer-events-none absolute left-2 top-1/2 size-3 -translate-y-1/2 text-muted-foreground" />
                      <Input
                        placeholder="Filtrar..."
                        value={filterSearch}
                        onChange={e => setFilterSearch(e.target.value)}
                        className="h-7 w-32 pl-6 text-xs"
                      />
                    </div>
                  </div>
                )}
              </div>
            </CardHeader>
            <CardContent className="p-0">
              {loading ? (
                <div className="overflow-auto">
                  <Table className="min-w-[640px] text-xs">
                    <TableHeader className="bg-muted/80">
                      <TableRow>
                        <TableHead className="px-3 py-2.5"><Skeleton className="h-3 w-14 rounded-md" /></TableHead>
                        <TableHead className="px-3 py-2.5"><Skeleton className="h-3 w-14 rounded-md" /></TableHead>
                        <TableHead className="px-3 py-2.5"><Skeleton className="h-3 w-14 rounded-md" /></TableHead>
                        <TableHead className="px-3 py-2.5"><Skeleton className="h-3 w-20 rounded-md" /></TableHead>
                        <TableHead className="px-3 py-2.5"><Skeleton className="h-3 w-14 rounded-md" /></TableHead>
                        <TableHead className="px-3 py-2.5"><Skeleton className="h-3 w-14 rounded-md" /></TableHead>
                        <TableHead className="px-3 py-2.5"><Skeleton className="ml-auto h-3 w-12 rounded-md" /></TableHead>
                        <TableHead className="px-3 py-2.5 w-8" />
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {Array.from({ length: 7 }).map((_, index) => (
                        <TableRow key={index} className="border-b border-border">
                          <TableCell className="px-3 py-2"><Skeleton className="h-4 w-24 rounded-md" /></TableCell>
                          <TableCell className="px-3 py-2"><Skeleton className="h-4 w-12 rounded-md" /></TableCell>
                          <TableCell className="px-3 py-2"><Skeleton className="h-4 w-20 rounded-md" /></TableCell>
                          <TableCell className="px-3 py-2"><Skeleton className="h-4 w-36 rounded-md" /></TableCell>
                          <TableCell className="px-3 py-2"><Skeleton className="h-4 w-24 rounded-md" /></TableCell>
                          <TableCell className="px-3 py-2"><Skeleton className="h-4 w-24 rounded-md" /></TableCell>
                          <TableCell className="px-3 py-2 text-right"><Skeleton className="ml-auto h-4 w-20 rounded-md" /></TableCell>
                          <TableCell className="px-3 py-2"><Skeleton className="h-4 w-4 rounded-sm" /></TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              ) : !preview ? (
                <div className="py-12 text-center text-xs text-muted-foreground">
                  Selecciona un período y haz clic en Previsualizar
                </div>
              ) : visibleCount === 0 ? (
                <div className="py-12 text-center text-xs text-muted-foreground">
                  No se encontraron facturas con los filtros aplicados.
                </div>
              ) : (
                <div className="overflow-auto">
                  <Table className="min-w-[640px] text-xs">
                    <TableHeader className="bg-muted/80">
                      <TableRow>
                        <TableHead className="px-3 py-2.5 text-[10px] uppercase tracking-wider font-medium text-muted-foreground">Estado</TableHead>
                        <TableHead className="px-3 py-2.5 text-[10px] uppercase tracking-wider font-medium text-muted-foreground">Estatus</TableHead>
                        <TableHead className="px-3 py-2.5 text-[10px] uppercase tracking-wider font-medium text-muted-foreground">Val. DGII</TableHead>
                        <TableHead className="px-3 py-2.5 text-[10px] uppercase tracking-wider font-medium text-muted-foreground">Fecha</TableHead>
                        <TableHead className="px-3 py-2.5 text-[10px] uppercase tracking-wider font-medium text-muted-foreground">Proveedor</TableHead>
                        <TableHead className="px-3 py-2.5 text-[10px] uppercase tracking-wider font-medium text-muted-foreground">RNC</TableHead>
                        <TableHead className="px-3 py-2.5 text-[10px] uppercase tracking-wider font-medium text-muted-foreground">NCF</TableHead>
                        <TableHead className="px-3 py-2.5 text-right text-[10px] uppercase tracking-wider font-medium text-muted-foreground">Total</TableHead>
                        <TableHead className="px-3 py-2.5 w-16 text-right">Acciones</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredPreview.map(inv => {
                        const status = getInvoiceStatus(inv, selectedFormat);
                        const cfg = STATUS_CONFIG[status as keyof typeof STATUS_CONFIG] || STATUS_CONFIG.ok;
                        return (
                          <TableRow key={inv.id} className={cn(
                            "border-b border-border transition-colors hover:bg-muted/50 group relative cursor-pointer",
                            status === "error" && "bg-red-500/[0.02]",
                            status === "blocked" && "bg-indigo-500/[0.04]",
                          )} onClick={() => {
                            setEditInvoice(inv);
                            setEditingFields({
                              ...inv.dgii_fields,
                              vendor_tax_id: inv.vendor_tax_id,
                              invoice_number: inv.invoice_number,
                              goods_services_type: inv.goods_services_type,
                            });
                          }}>
                            <TableCell className="px-3 py-2">
                              <Badge className={cn("gap-1 px-1.5 py-0.5 text-[9px] font-medium", cfg.badge)}>
                                {cfg.icon}{cfg.label}
                              </Badge>
                            </TableCell>
                            <TableCell className="px-3 py-2">
                              <span
                                title={inv.reporting_note || inv.macro_status}
                                className={cn(
                                  "inline-flex items-center gap-1 text-[9px] font-mono font-medium",
                                  inv.reporting_state === "blocked_confirmed_ncf"
                                    ? "text-indigo-700"
                                    : inv.macro_status === "OK"
                                      ? "text-emerald-600"
                                      : "text-red-500"
                                )}
                              >
                                {inv.reporting_state === "blocked_confirmed_ncf" ? (
                                  <>
                                    <ShieldCheck className="size-3" />
                                    BLOQ
                                  </>
                                ) : inv.macro_status === "OK" ? (
                                  <>
                                    <CheckCircle2 className="size-3" />
                                    OK
                                  </>
                                ) : (
                                  <>
                                    <XCircle className="size-3" />
                                    ERROR
                                  </>
                                )}
                              </span>
                            </TableCell>
                            <TableCell className="px-3 py-2">
                              <DgiiValidationBadge status={inv.dgii_validation_status} />
                            </TableCell>
                            <TableCell className="px-3 py-2 text-muted-foreground whitespace-nowrap">{inv.invoice_date || "—"}</TableCell>
                            <TableCell className="px-3 py-2 max-w-[160px] truncate font-medium group-hover:text-clip group-hover:overflow-visible group-hover:bg-background group-hover:shadow-sm group-hover:z-10 group-hover:relative" title={inv.vendor_name || ""}>{inv.vendor_name || "—"}</TableCell>
                            <TableCell className="px-3 py-2 font-mono text-[11px]">{inv.vendor_tax_id || <span className="text-red-400">Falta</span>}</TableCell>
                            <TableCell className="px-3 py-2 font-mono text-[11px]">{inv.invoice_number || <span className="text-red-400">Falta</span>}</TableCell>
                            <TableCell className="px-3 py-2 text-right font-mono tabular-nums">{fmtCurrency(inv.total_amount)}</TableCell>
                            <TableCell className="px-3 py-1.5 w-16" onClick={e => e.stopPropagation()}>
                              <div className="flex items-center gap-1.5 justify-end">
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-6 w-6 rounded-md hover:bg-muted"
                                  title="Validar ante DGII"
                                  disabled={validatingIds[inv.id]}
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    void handleValidateInvoice(inv.id);
                                  }}
                                >
                                  {validatingIds[inv.id] ? (
                                    <Loader2 className="size-3 animate-spin text-primary" />
                                  ) : (
                                    <Globe className="size-3 text-muted-foreground hover:text-primary transition-colors" />
                                  )}
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-6 w-6 rounded-md hover:bg-muted"
                                  title="Editar"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    setEditInvoice(inv);
                                    setEditingFields({
                                      ...inv.dgii_fields,
                                      vendor_tax_id: inv.vendor_tax_id,
                                      invoice_number: inv.invoice_number,
                                      goods_services_type: inv.goods_services_type,
                                    });
                                  }}
                                >
                                  <PencilLine className="size-3 text-muted-foreground hover:text-foreground transition-colors" />
                                </Button>
                              </div>
                            </TableCell>
                          </TableRow>
                        );
                      })}
                    </TableBody>
                  </Table>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Confirmed NCF warning */}
          {preview && blockedConfirmedCount > 0 && (
            <Card className="border-indigo-200 bg-indigo-50/60">
              <CardContent className="py-2.5 px-4 text-[11px] text-indigo-700 flex items-center gap-2">
                <ShieldCheck className="size-3.5" />
                {blockedConfirmedCount} factura(s) tienen NCF ya confirmado por DGII y están bloqueadas para re-reporte.
              </CardContent>
            </Card>
          )}

          {/* Download CTA */}
          {preview && visibleCount > 0 && (
            <Card className={cn("border-2", canExport ? "border-primary/30" : "border-border")}>
              <CardContent className="py-4 px-4">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                  <div>
                    <p className="text-sm font-semibold">
                      {fmt.label}{dateFrom || dateTo
                        ? ` — ${dateFrom || "—"} al ${dateTo || "—"}`
                        : ` — ${periodLabel(period)}`}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {reportableCount} facturas reportables · {fmtCurrency(preview.total_amount + preview.total_tax)} total con ITBIS
                      {preview.issues > 0 && ` · ⚠ ${preview.issues} con problemas`}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      disabled={!canExport || downloading}
                      onClick={handleDownload}
                      className="shrink-0"
                    >
                      {downloading ? (
                        <><Loader2 className="size-4 mr-2 animate-spin" />Descargando...</>
                      ) : (
                        <><Download className="size-4 mr-2" />Descargar .TXT (DGII)</>
                      )}
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>

      {/* Confirmation dialog for auto-fixes */}
      <AlertDialog open={!!confirmFix} onOpenChange={o => { if (!o) setConfirmFix(null); }}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle className="flex items-center gap-2 text-base">
              {confirmFix ? FIX_CONFIG[confirmFix]?.icon : null}
              {confirmFix ? FIX_CONFIG[confirmFix]?.title : ""}
            </AlertDialogTitle>
            <AlertDialogDescription className="text-xs space-y-3">
              <p>{confirmFix ? FIX_CONFIG[confirmFix]?.desc : ""}</p>
              <div className="rounded-md border border-amber-200 bg-amber-50 p-3 text-amber-800">
                <p className="font-semibold text-[11px] flex items-center gap-1.5 mb-1">
                  <AlertTriangle className="size-3.5" /> ⚠ Acción sensible
                </p>
                <p className="text-[11px] leading-relaxed">
                  {confirmFix ? FIX_CONFIG[confirmFix]?.warning : ""}
                </p>
                <p className="text-[10px] mt-2 text-amber-600">
                  Esta operación no se puede deshacer automáticamente. Revisa los cambios antes de continuar.
                </p>
              </div>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="h-8 text-xs">Cancelar</AlertDialogCancel>
            <AlertDialogAction onClick={handleConfirmFix} disabled={fixing} className="h-8 text-xs">
              {fixing ? <Loader2 className="size-3 mr-1 animate-spin" /> : <WandSparkles className="size-3 mr-1" />}
              {fixing ? "Aplicando..." : "Sí, aplicar corrección"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* ── Edit Invoice Dialog (Review Split View) ── */}
      <Dialog open={!!editInvoice} onOpenChange={o => { if (!o) { setEditInvoice(null); setEditingFields({}); } }}>
        <DialogContent className="sm:max-w-7xl h-[90vh] max-h-[90vh] overflow-hidden flex flex-col p-0 bg-background">
          <DialogHeader className="px-6 pt-5 pb-3 shrink-0 border-b">
            <DialogTitle className="flex items-center justify-between text-sm">
              <span className="flex items-center gap-2 font-semibold">
                <PencilLine className="size-4 text-primary" />
                Revisión y Edición de Factura DGII
              </span>
              {editInvoice && editInvoice.macro_status !== "OK" && (
                <Badge variant="destructive" className="text-[9px] px-1.5 py-0">
                  <XCircle className="size-2.5 mr-0.5" />{editInvoice.macro_status}
                </Badge>
              )}
            </DialogTitle>
            <DialogDescription className="text-xs">
              {editInvoice && (
                <span className="flex items-center gap-2 flex-wrap mt-0.5">
                  <span className="font-mono font-medium text-foreground">{editInvoice.invoice_number || "Sin NCF"}</span>
                  <span className="text-muted-foreground">·</span>
                  <span className="font-medium">{editInvoice.vendor_name || "Proveedor desconocido"}</span>
                  <span className="text-muted-foreground">·</span>
                  <span className="tabular-nums font-mono">{fmtCurrency(editInvoice.total_amount)}</span>
                </span>
              )}
            </DialogDescription>
          </DialogHeader>

          {editInvoice && (
            <div className="flex-1 min-h-0 flex overflow-hidden">
              {/* Left Column: Form Editor */}
              <div className="w-1/2 overflow-y-auto border-r flex flex-col">
                <DgiiFieldEditor
                  inv={editInvoice}
                  format={selectedFormat}
                  fields={editingFields}
                  referenceOptions={referenceOptions}
                  onChange={(k, v) => setEditingFields(prev => ({...prev, [k]: v}))}
                  saving={savingField}
                  onSave={async () => {
                    setSavingField(true);
                    try {
                      await updateDgiiFields(editInvoice.id, editingFields);
                      await runPreview();
                      setEditInvoice(null);
                      setEditingFields({});
                    } catch (e: any) {
                      setError(e.message || "Error al guardar");
                    } finally {
                      setSavingField(false);
                    }
                  }}
                  onValidate={() => handleValidateInvoice(editInvoice.id)}
                  validating={validatingIds[editInvoice.id]}
                />
              </div>

              {/* Right Column: Invoice Viewer */}
              <div className="w-1/2 bg-slate-50 flex flex-col h-full overflow-hidden">
                <div className="flex items-center justify-between px-4 py-2 border-b bg-white shrink-0">
                  <span className="text-xs font-semibold text-muted-foreground flex items-center gap-1.5">
                    <FileText className="size-3.5 text-primary" /> Documento Adjunto
                  </span>
                  {editInvoice.file_url && (
                    <a
                      href={editInvoice.file_url}
                      target="_blank"
                      rel="noreferrer"
                      className="text-[10px] text-primary hover:underline font-medium flex items-center gap-1"
                    >
                      <ExternalLink className="size-3" /> Abrir original en pestaña nueva
                    </a>
                  )}
                </div>
                <div className="flex-1 overflow-auto p-4 flex items-center justify-center min-h-0">
                  {editInvoice.file_url ? (
                    editInvoice.file_path?.toLowerCase().endsWith(".pdf") || editInvoice.file_url.toLowerCase().includes(".pdf") ? (
                      <iframe
                        src={editInvoice.file_url}
                        className="w-full h-full border rounded-md shadow-xs bg-white"
                        title="Visor PDF Factura"
                        sandbox="allow-scripts allow-same-origin"
                      />
                    ) : (
                      <div className="relative max-w-full max-h-full flex items-center justify-center overflow-auto rounded-md border shadow-xs bg-white p-2">
                        <img
                          src={editInvoice.file_url}
                          alt="Documento de Factura"
                          className="max-w-full max-h-full object-contain"
                        />
                      </div>
                    )
                  ) : (
                    <div className="flex flex-col items-center justify-center text-muted-foreground gap-2 text-center p-6">
                      <FileText className="size-12 opacity-40 text-slate-400" />
                      <span className="text-xs font-medium">No hay imagen o archivo disponible para este comprobante</span>
                      <span className="text-[10px] text-slate-400">Origen de extracción: {editInvoice.source_type || "manual"}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* ── Submission success message ── */}
      {submissionMessage && (
        <Card className="border-l-4 border-l-emerald-500 bg-emerald-50/60">
          <CardContent className="py-3 px-4 flex items-center justify-between gap-3">
            <div className="flex items-center gap-2 text-xs text-emerald-800">
              <CheckCircle2 className="size-4 shrink-0" />
              <span>{submissionMessage}</span>
            </div>
            <div className="flex items-center gap-2 shrink-0">
              <Button
                variant="outline" size="sm"
                className="h-7 text-[10px] gap-1.5"
                onClick={() => window.location.href = "/dashboard/dgii/envios"}
              >
                <ExternalLink className="size-3" />
                Ir a Envíos
              </Button>
              <Button
                variant="ghost" size="sm"
                className="h-7 w-7 p-0"
                onClick={() => setSubmissionMessage(null)}
              >
                <XCircle className="size-3.5 text-muted-foreground" />
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── Post-download submission dialog ── */}
      <AlertDialog open={showSubmissionDialog} onOpenChange={o => { if (!o) setShowSubmissionDialog(false); }}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle className="flex items-center gap-2 text-base">
              <SendIcon className="size-4 text-primary" />
              ¿Cómo fue el resultado al cargar el reporte?
            </AlertDialogTitle>
            <AlertDialogDescription className="text-xs space-y-3">
              <span>
                Reporte <strong>{selectedFormat.replace("dgii_", "")}</strong> para <strong>{periodLabel(submittingPeriod)}</strong> —
                <strong> {submittingIds.length}</strong> factura(s).
              </span>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="flex flex-col gap-2 px-6 pb-4">
            <Button
              variant="default"
              size="sm"
              className="h-9 text-xs justify-start gap-2 w-full"
              disabled={submissionSaving}
              onClick={() => handleMarkAsSubmitted("confirmed")}
            >
              {submissionSaving ? <Loader2 className="size-3.5 animate-spin" /> : <CheckCircle2 className="size-3.5 text-emerald-300" />}
              Aceptado — marcar como enviadas
            </Button>
            <Button
              variant="outline"
              size="sm"
              className="h-9 text-xs justify-start gap-2 w-full"
              disabled={submissionSaving}
              onClick={() => handleMarkAsSubmitted("pending_confirm")}
            >
              {submissionSaving ? <Loader2 className="size-3.5 animate-spin" /> : <AlertTriangle className="size-3.5 text-amber-500" />}
              Tuvo errores — lo revisaré en Envíos
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="h-9 text-xs justify-center gap-2 w-full mt-1"
              disabled={submissionSaving}
              onClick={() => handleMarkAsSubmitted("pending_upload")}
            >
              {submissionSaving ? <Loader2 className="size-3.5 animate-spin" /> : <SendIcon className="size-3.5 text-muted-foreground" />}
              No lo he subido aún — lo haré después
            </Button>
          </div>
        </AlertDialogContent>
      </AlertDialog>

      {/* ── Spreadsheet View Dialog ── */}
      <Dialog open={spreadsheetOpen} onOpenChange={setSpreadsheetOpen}>
        <DialogContent className="sm:max-w-[95vw] h-[90vh] max-h-[90vh] overflow-hidden p-0 flex flex-col">
          <DialogHeader className="px-6 pt-5 pb-0">
            <DialogTitle className="flex items-center gap-2 text-sm">
              <Sheet className="size-4 text-primary" />
              Vista Plantilla — {REPORTS.find(f => f.id === selectedFormat)?.label || selectedFormat}
            </DialogTitle>
            <DialogDescription className="text-xs">
              Vista de columnas idéntica a la plantilla de Excel de la DGII. Click en cualquier celda para editar.
            </DialogDescription>
          </DialogHeader>
          <div className="px-6 pb-5 flex-1 overflow-hidden flex flex-col">
            <DgiiSpreadsheetView
              invoices={filteredPreview}
              format={selectedFormat}
              onRefresh={async () => { await runPreview(); }}
              onSelectInvoice={(inv) => {
                setEditInvoice(inv);
                setEditingFields({
                  ...inv.dgii_fields,
                  vendor_tax_id: inv.vendor_tax_id,
                  invoice_number: inv.invoice_number,
                  goods_services_type: inv.goods_services_type,
                });
              }}
              onValidateInvoice={handleValidateInvoice}
              validatingIds={validatingIds}
              onBulkValidate={handleBulkValidate}
              isBulkValidating={bulkValidating}
            />
          </div>
        </DialogContent>
      </Dialog>

      {/* ── Error Review Wizard Dialog ── */}
      <DgiiErrorReviewWizard
        open={errorReviewOpen}
        onClose={async (resolvedAny) => {
          setErrorReviewOpen(false);
          if (resolvedAny) {
            await runPreview();
            const summary = await getDgiiPendingSummary();
            setPendingSummary(summary);
          }
        }}
        format={selectedFormat}
        period={period}
      />
    </div>
  );
}
