"""add_lago_mio_billing_fields

Revision ID: 1ba6aefd32a7
Revises: 9e884bd4ddb3
Create Date: 2026-06-27 00:48:39.249608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba6aefd32a7'
down_revision: Union[str, Sequence[str], None] = '9e884bd4ddb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_subscriptions', sa.Column('lago_subscription_id', sa.String(length=64), nullable=True))
    op.add_column('organization_subscriptions', sa.Column('lago_customer_id', sa.String(length=64), nullable=True))
    op.add_column('organization_subscriptions', sa.Column('lago_plan_code', sa.String(length=100), nullable=True))
    op.add_column('organization_subscriptions', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('organization_subscriptions', sa.Column('mio_customer_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_organization_subscriptions_lago_customer_id'), 'organization_subscriptions', ['lago_customer_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_lago_subscription_id'), 'organization_subscriptions', ['lago_subscription_id'], unique=False)
    op.add_column('subscription_plans', sa.Column('price_dop', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('subscription_plans', sa.Column('lago_plan_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'lago_plan_code')
    op.drop_column('subscription_plans', 'price_dop')
    op.drop_index(op.f('ix_organization_subscriptions_lago_subscription_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_lago_customer_id'), table_name='organization_subscriptions')
    op.drop_column('organization_subscriptions', 'mio_customer_token')
    op.drop_column('organization_subscriptions', 'payment_method')
    op.drop_column('organization_subscriptions', 'lago_plan_code')
    op.drop_column('organization_subscriptions', 'lago_customer_id')
    op.drop_column('organization_subscriptions', 'lago_subscription_id')
    # ### end Alembic commands ###
