"""add_alanube_certification_fields

Revision ID: 20c2ae81fe34
Revises: 5eeede167873
Create Date: 2026-05-26 17:31:54.162974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c2ae81fe34'
down_revision: Union[str, Sequence[str], None] = '5eeede167873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS certification_status VARCHAR DEFAULT 'none' NOT NULL")
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS alanube_company_id VARCHAR")
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS alanube_environment VARCHAR")
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS certificate_uploaded_at TIMESTAMP WITH TIME ZONE")
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS economic_activity VARCHAR")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS economic_activity")
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS certificate_uploaded_at")
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS alanube_environment")
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS alanube_company_id")
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS certification_status")
    # ### end Alembic commands ###
