"""add_alanube_certification_fields

Revision ID: 20c2ae81fe34
Revises: 5eeede167873
Create Date: 2026-05-26 17:31:54.162974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c2ae81fe34'
down_revision: Union[str, Sequence[str], None] = '5eeede167873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('certification_status', sa.String(), server_default='none', nullable=False))
    op.add_column('organizations', sa.Column('alanube_company_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('alanube_environment', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('certificate_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('economic_activity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'economic_activity')
    op.drop_column('organizations', 'certificate_uploaded_at')
    op.drop_column('organizations', 'alanube_environment')
    op.drop_column('organizations', 'alanube_company_id')
    op.drop_column('organizations', 'certification_status')
    # ### end Alembic commands ###
