"""add certification tracking columns

Revision ID: 35e1e54655e0
Revises: b776fa27a514
Create Date: 2026-05-28 08:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e1e54655e0'
down_revision: Union[str, Sequence[str], None] = 'b776fa27a514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS certification_step VARCHAR DEFAULT '0' NOT NULL")
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS is_certification_completed BOOLEAN DEFAULT false NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS is_certification_completed")
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS certification_step")
    # ### end Alembic commands ###
