"""add_user_job_title_org_contact_fields

Revision ID: 36416ccaebf8
Revises: d24fe2e1132d
Create Date: 2026-05-24 19:14:47.060356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36416ccaebf8'
down_revision: Union[str, Sequence[str], None] = 'd24fe2e1132d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS email_contact VARCHAR")
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS website VARCHAR")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS job_title VARCHAR")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS job_title")
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS website")
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS email_contact")
    # ### end Alembic commands ###
