"""add_user_job_title_org_contact_fields

Revision ID: 36416ccaebf8
Revises: d24fe2e1132d
Create Date: 2026-05-24 19:14:47.060356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36416ccaebf8'
down_revision: Union[str, Sequence[str], None] = 'd24fe2e1132d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('email_contact', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_title')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'email_contact')
    # ### end Alembic commands ###
