"""add_pending_cancel_addon_columns

Revision ID: 366e6c78f69b
Revises: f792438e9fa1
Create Date: 2026-06-30 04:17:34.403411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366e6c78f69b'
down_revision: Union[str, Sequence[str], None] = 'f792438e9fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_subscriptions', sa.Column('pending_cancel_entity_slots', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('organization_subscriptions', sa.Column('pending_cancel_user_slots', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('organization_subscriptions', sa.Column('pending_cancel_ai_blocks', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('organization_subscriptions', sa.Column('pending_cancel_storage_blocks', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('user_subscriptions', sa.Column('pending_cancel_entity_slots', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'pending_cancel_entity_slots')
    op.drop_column('organization_subscriptions', 'pending_cancel_storage_blocks')
    op.drop_column('organization_subscriptions', 'pending_cancel_ai_blocks')
    op.drop_column('organization_subscriptions', 'pending_cancel_user_slots')
    op.drop_column('organization_subscriptions', 'pending_cancel_entity_slots')
    # ### end Alembic commands ###
