"""add_auto_renew_to_user_subscription

Revision ID: 40fb9726689c
Revises: 80dfa2c3e0dd
Create Date: 2026-06-28 00:34:22.859873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fb9726689c'
down_revision: Union[str, Sequence[str], None] = '80dfa2c3e0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'auto_renew')
    # ### end Alembic commands ###
