"""add_invoice_payment_fields

Revision ID: 428a67e30bf0
Revises: 36416ccaebf8
Create Date: 2026-05-25 16:24:24.070257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428a67e30bf0'
down_revision: Union[str, Sequence[str], None] = '36416ccaebf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_condition VARCHAR(20)")
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS due_date TIMESTAMP WITH TIME ZONE")
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_date TIMESTAMP WITH TIME ZONE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE invoices DROP COLUMN IF EXISTS payment_date")
    op.execute("ALTER TABLE invoices DROP COLUMN IF EXISTS due_date")
    op.execute("ALTER TABLE invoices DROP COLUMN IF EXISTS payment_condition")
    # ### end Alembic commands ###
