"""add_invoice_payment_fields

Revision ID: 428a67e30bf0
Revises: 36416ccaebf8
Create Date: 2026-05-25 16:24:24.070257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428a67e30bf0'
down_revision: Union[str, Sequence[str], None] = '36416ccaebf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('payment_condition', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_date')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'payment_condition')
    # ### end Alembic commands ###
