"""add_upload_link_id_to_pending_upload

Revision ID: 465d130b62a0
Revises: 89b35633dc35
Create Date: 2026-06-06 13:30:18.076524

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '465d130b62a0'
down_revision: Union[str, Sequence[str], None] = '89b35633dc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_cn_deleted_at")
    op.execute("DROP INDEX IF EXISTS ix_cn_is_deleted")
    op.execute("DROP INDEX IF EXISTS uq_cn_tenant_org_ncf")
    op.execute("CREATE INDEX IF NOT EXISTS ix_credit_notes_credit_note_number ON credit_notes (credit_note_number)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_credit_notes_deleted_at ON credit_notes (deleted_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_credit_notes_invoice_id ON credit_notes (invoice_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_credit_notes_is_deleted ON credit_notes (is_deleted)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_credit_notes_ncf_modified ON credit_notes (ncf_modified)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_credit_notes_organization_id ON credit_notes (organization_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_credit_notes_status ON credit_notes (status)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_credit_notes_tenant_id ON credit_notes (tenant_id)")
    op.execute("ALTER TABLE credit_notes DROP CONSTRAINT IF EXISTS credit_notes_linked_by_fkey")
    op.execute("ALTER TABLE credit_notes DROP CONSTRAINT IF EXISTS credit_notes_deleted_by_fkey")
    op.execute("ALTER TABLE credit_notes DROP CONSTRAINT IF EXISTS credit_notes_tenant_id_fkey")
    op.execute("ALTER TABLE credit_notes DROP CONSTRAINT IF EXISTS credit_notes_organization_id_fkey")
    op.execute("ALTER TABLE credit_notes DROP CONSTRAINT IF EXISTS credit_notes_created_by_fkey")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'credit_notes'::regclass
                AND conname = 'fk_credit_notes_tenant_id'
            ) THEN
                ALTER TABLE credit_notes
                ADD CONSTRAINT fk_credit_notes_tenant_id
                FOREIGN KEY (tenant_id) REFERENCES tenants(id);
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'credit_notes'::regclass
                AND conname = 'fk_credit_notes_organization_id'
            ) THEN
                ALTER TABLE credit_notes
                ADD CONSTRAINT fk_credit_notes_organization_id
                FOREIGN KEY (organization_id) REFERENCES organizations(id);
            END IF;
        END $$;
    """)
    op.execute("ALTER TABLE pending_uploads ADD COLUMN IF NOT EXISTS upload_link_id UUID")
    op.execute("CREATE INDEX IF NOT EXISTS ix_pending_uploads_upload_link_id ON pending_uploads (upload_link_id)")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'pending_uploads'::regclass
                AND conname = 'fk_pending_uploads_upload_link_id'
            ) THEN
                ALTER TABLE pending_uploads
                ADD CONSTRAINT fk_pending_uploads_upload_link_id
                FOREIGN KEY (upload_link_id) REFERENCES upload_links(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE pending_uploads DROP CONSTRAINT IF EXISTS fk_pending_uploads_upload_link_id")
    op.execute("DROP INDEX IF EXISTS ix_pending_uploads_upload_link_id")
    op.execute("ALTER TABLE pending_uploads DROP COLUMN IF EXISTS upload_link_id")
    op.execute("ALTER TABLE credit_notes DROP CONSTRAINT IF EXISTS fk_credit_notes_tenant_id")
    op.execute("ALTER TABLE credit_notes DROP CONSTRAINT IF EXISTS fk_credit_notes_organization_id")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'credit_notes'::regclass
                AND conname = 'credit_notes_created_by_fkey'
            ) THEN
                ALTER TABLE credit_notes
                ADD CONSTRAINT credit_notes_created_by_fkey
                FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'credit_notes'::regclass
                AND conname = 'credit_notes_organization_id_fkey'
            ) THEN
                ALTER TABLE credit_notes
                ADD CONSTRAINT credit_notes_organization_id_fkey
                FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'credit_notes'::regclass
                AND conname = 'credit_notes_tenant_id_fkey'
            ) THEN
                ALTER TABLE credit_notes
                ADD CONSTRAINT credit_notes_tenant_id_fkey
                FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'credit_notes'::regclass
                AND conname = 'credit_notes_deleted_by_fkey'
            ) THEN
                ALTER TABLE credit_notes
                ADD CONSTRAINT credit_notes_deleted_by_fkey
                FOREIGN KEY (deleted_by) REFERENCES users(id) ON DELETE SET NULL;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'credit_notes'::regclass
                AND conname = 'credit_notes_linked_by_fkey'
            ) THEN
                ALTER TABLE credit_notes
                ADD CONSTRAINT credit_notes_linked_by_fkey
                FOREIGN KEY (linked_by) REFERENCES users(id) ON DELETE SET NULL;
            END IF;
        END $$;
    """)
    op.execute("DROP INDEX IF EXISTS ix_credit_notes_tenant_id")
    op.execute("DROP INDEX IF EXISTS ix_credit_notes_status")
    op.execute("DROP INDEX IF EXISTS ix_credit_notes_organization_id")
    op.execute("DROP INDEX IF EXISTS ix_credit_notes_ncf_modified")
    op.execute("DROP INDEX IF EXISTS ix_credit_notes_is_deleted")
    op.execute("DROP INDEX IF EXISTS ix_credit_notes_invoice_id")
    op.execute("DROP INDEX IF EXISTS ix_credit_notes_deleted_at")
    op.execute("DROP INDEX IF EXISTS ix_credit_notes_credit_note_number")
    op.execute("CREATE INDEX IF NOT EXISTS uq_cn_tenant_org_ncf ON credit_notes (tenant_id, organization_id, credit_note_number) WHERE ((credit_note_number IS NOT NULL) AND (is_deleted = false))")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cn_is_deleted ON credit_notes (is_deleted)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cn_deleted_at ON credit_notes (deleted_at)")
    # ### end Alembic commands ###
