"""add_upload_link_id_to_pending_upload

Revision ID: 465d130b62a0
Revises: 89b35633dc35
Create Date: 2026-06-06 13:30:18.076524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import GUID


# revision identifiers, used by Alembic.
revision: str = '465d130b62a0'
down_revision: Union[str, Sequence[str], None] = '89b35633dc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cn_deleted_at'), table_name='credit_notes')
    op.drop_index(op.f('ix_cn_is_deleted'), table_name='credit_notes')
    op.drop_index(op.f('uq_cn_tenant_org_ncf'), table_name='credit_notes', postgresql_where='((credit_note_number IS NOT NULL) AND (is_deleted = false))')
    op.create_index(op.f('ix_credit_notes_credit_note_number'), 'credit_notes', ['credit_note_number'], unique=False)
    op.create_index(op.f('ix_credit_notes_deleted_at'), 'credit_notes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_credit_notes_invoice_id'), 'credit_notes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_is_deleted'), 'credit_notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_credit_notes_ncf_modified'), 'credit_notes', ['ncf_modified'], unique=False)
    op.create_index(op.f('ix_credit_notes_organization_id'), 'credit_notes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_status'), 'credit_notes', ['status'], unique=False)
    op.create_index(op.f('ix_credit_notes_tenant_id'), 'credit_notes', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('credit_notes_linked_by_fkey'), 'credit_notes', type_='foreignkey')
    op.drop_constraint(op.f('credit_notes_deleted_by_fkey'), 'credit_notes', type_='foreignkey')
    op.drop_constraint(op.f('credit_notes_tenant_id_fkey'), 'credit_notes', type_='foreignkey')
    op.drop_constraint(op.f('credit_notes_organization_id_fkey'), 'credit_notes', type_='foreignkey')
    op.drop_constraint(op.f('credit_notes_created_by_fkey'), 'credit_notes', type_='foreignkey')
    op.create_foreign_key(None, 'credit_notes', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'credit_notes', 'organizations', ['organization_id'], ['id'])
    op.add_column('pending_uploads', sa.Column('upload_link_id', GUID(length=32), nullable=True))
    op.create_index(op.f('ix_pending_uploads_upload_link_id'), 'pending_uploads', ['upload_link_id'], unique=False)
    op.create_foreign_key(None, 'pending_uploads', 'upload_links', ['upload_link_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_uploads', type_='foreignkey')
    op.drop_index(op.f('ix_pending_uploads_upload_link_id'), table_name='pending_uploads')
    op.drop_column('pending_uploads', 'upload_link_id')
    op.drop_constraint(None, 'credit_notes', type_='foreignkey')
    op.drop_constraint(None, 'credit_notes', type_='foreignkey')
    op.create_foreign_key(op.f('credit_notes_created_by_fkey'), 'credit_notes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('credit_notes_organization_id_fkey'), 'credit_notes', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('credit_notes_tenant_id_fkey'), 'credit_notes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('credit_notes_deleted_by_fkey'), 'credit_notes', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('credit_notes_linked_by_fkey'), 'credit_notes', 'users', ['linked_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_credit_notes_tenant_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_status'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_organization_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_ncf_modified'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_is_deleted'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_invoice_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_deleted_at'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_number'), table_name='credit_notes')
    op.create_index(op.f('uq_cn_tenant_org_ncf'), 'credit_notes', ['tenant_id', 'organization_id', 'credit_note_number'], unique=True, postgresql_where='((credit_note_number IS NOT NULL) AND (is_deleted = false))')
    op.create_index(op.f('ix_cn_is_deleted'), 'credit_notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_cn_deleted_at'), 'credit_notes', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
