"""initial_schema

Revision ID: 50c279d55c20
Revises: 
Create Date: 2026-05-22 21:14:33.919573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '50c279d55c20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('actor_email', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('visibility', sa.String(length=10), server_default='client', nullable=False),
    sa.Column('snapshot_before', sa.JSON(), nullable=True),
    sa.Column('snapshot_after', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_visibility'), 'audit_logs', ['visibility'], unique=False)
    op.create_index('ix_auditlog_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_auditlog_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_auditlog_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_auditlog_org_tenant', 'audit_logs', ['organization_id', 'tenant_id'], unique=False)
    op.create_index('ix_auditlog_visibility', 'audit_logs', ['visibility'], unique=False)
    op.create_table('integration_connections',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intconn_org_provider', 'integration_connections', ['tenant_id', 'organization_id', 'provider'], unique=False)
    op.create_index(op.f('ix_integration_connections_organization_id'), 'integration_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_integration_connections_provider'), 'integration_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_connections_tenant_id'), 'integration_connections', ['tenant_id'], unique=False)
    op.create_table('reference_data',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label_es', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refdata_domain', 'reference_data', ['domain'], unique=False)
    op.create_index('ix_refdata_domain_code', 'reference_data', ['domain', 'code'], unique=True)
    op.create_table('tenants',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('organizations',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('supabase_uid', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('verification_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('account_mappings',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_mappings_org_provider', 'account_mappings', ['tenant_id', 'organization_id', 'provider'], unique=False)
    op.create_index(op.f('ix_account_mappings_organization_id'), 'account_mappings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_account_mappings_provider'), 'account_mappings', ['provider'], unique=False)
    op.create_index(op.f('ix_account_mappings_tenant_id'), 'account_mappings', ['tenant_id'], unique=False)
    op.create_table('dgii_submissions',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('format', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('invoice_ids', sa.JSON(), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', app.database.GUID(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dgii_submissions_lookup', 'dgii_submissions', ['tenant_id', 'organization_id', 'format', 'period'], unique=False)
    op.create_index(op.f('ix_dgii_submissions_organization_id'), 'dgii_submissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dgii_submissions_period'), 'dgii_submissions', ['period'], unique=False)
    op.create_index(op.f('ix_dgii_submissions_tenant_id'), 'dgii_submissions', ['tenant_id'], unique=False)
    op.create_table('export_profiles',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_profiles_org', 'export_profiles', ['tenant_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_export_profiles_organization_id'), 'export_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_export_profiles_tenant_id'), 'export_profiles', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('processed_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_extracted_data', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('audit_flags', sa.Text(), nullable=True),
    sa.Column('openai_tokens_used', sa.Integer(), nullable=True),
    sa.Column('openai_cost_usd', sa.Float(), nullable=True),
    sa.Column('openai_model_used', sa.String(), nullable=True),
    sa.Column('openai_processing_time', sa.Float(), nullable=True),
    sa.Column('vendor_country', sa.String(length=3), nullable=True),
    sa.Column('vendor_tax_id', sa.String(), nullable=True),
    sa.Column('vendor_fiscal_address', sa.Text(), nullable=True),
    sa.Column('line_items_data', sa.Text(), nullable=True),
    sa.Column('country_detection_method', sa.String(), nullable=True),
    sa.Column('country_confidence', sa.Float(), nullable=True),
    sa.Column('goods_services_type', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('quality_report', sa.Text(), nullable=True),
    sa.Column('original_xml_data', sa.Text(), nullable=True),
    sa.Column('ecf_type', sa.String(length=2), nullable=True),
    sa.Column('batch_id', app.database.GUID(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', app.database.GUID(length=32), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_type', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_cancelled_at'), 'invoices', ['cancelled_at'], unique=False)
    op.create_index(op.f('ix_invoices_deleted_at'), 'invoices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_invoices_filename'), 'invoices', ['filename'], unique=False)
    op.create_index('ix_invoices_ncf', 'invoices', ['tenant_id', 'organization_id', 'invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index('ix_invoices_source', 'invoices', ['tenant_id', 'organization_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index('ix_invoices_tenant_org', 'invoices', ['tenant_id', 'organization_id'], unique=False)
    op.create_index('ix_invoices_vendor_date', 'invoices', ['tenant_id', 'organization_id', 'vendor_tax_id', 'invoice_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_tenant_org', 'notifications', ['tenant_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('settings',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'organization_id', 'key', name='uq_settings_tenant_org_key')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_index('ix_settings_tenant_org', 'settings', ['tenant_id', 'organization_id'], unique=False)
    op.create_table('user_organizations',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('user_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org')
    )
    op.create_index(op.f('ix_user_organizations_organization_id'), 'user_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organizations_user_id'), 'user_organizations', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('user_id', app.database.GUID(length=32), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_settings_user_key')
    )
    op.create_index(op.f('ix_user_settings_key'), 'user_settings', ['key'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('events', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_organization_id'), 'webhook_endpoints', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_tenant_id'), 'webhook_endpoints', ['tenant_id'], unique=False)
    op.create_index('ix_webhooks_tenant_org', 'webhook_endpoints', ['tenant_id', 'organization_id'], unique=False)
    op.create_table('invoice_dgii_statuses',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('invoice_id', app.database.GUID(length=32), nullable=False),
    sa.Column('format', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submission_id', app.database.GUID(length=32), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('report_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['dgii_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_dgii_status_format_period', 'invoice_dgii_statuses', ['format', 'period'], unique=False)
    op.create_index('ix_inv_dgii_status_lookup', 'invoice_dgii_statuses', ['invoice_id', 'format', 'status'], unique=False)
    op.create_index(op.f('ix_invoice_dgii_statuses_invoice_id'), 'invoice_dgii_statuses', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_dgii_statuses_period'), 'invoice_dgii_statuses', ['period'], unique=False)
    op.create_index(op.f('ix_invoice_dgii_statuses_submission_id'), 'invoice_dgii_statuses', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_dgii_statuses_submission_id'), table_name='invoice_dgii_statuses')
    op.drop_index(op.f('ix_invoice_dgii_statuses_period'), table_name='invoice_dgii_statuses')
    op.drop_index(op.f('ix_invoice_dgii_statuses_invoice_id'), table_name='invoice_dgii_statuses')
    op.drop_index('ix_inv_dgii_status_lookup', table_name='invoice_dgii_statuses')
    op.drop_index('ix_inv_dgii_status_format_period', table_name='invoice_dgii_statuses')
    op.drop_table('invoice_dgii_statuses')
    op.drop_index('ix_webhooks_tenant_org', table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_tenant_id'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_organization_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_key'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_organizations_user_id'), table_name='user_organizations')
    op.drop_index(op.f('ix_user_organizations_organization_id'), table_name='user_organizations')
    op.drop_table('user_organizations')
    op.drop_index('ix_settings_tenant_org', table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index('ix_notifications_tenant_org', table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_invoices_vendor_date', table_name='invoices')
    op.drop_index('ix_invoices_tenant_org', table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index('ix_invoices_source', table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index('ix_invoices_ncf', table_name='invoices')
    op.drop_index(op.f('ix_invoices_filename'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_deleted_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_cancelled_at'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_export_profiles_tenant_id'), table_name='export_profiles')
    op.drop_index(op.f('ix_export_profiles_organization_id'), table_name='export_profiles')
    op.drop_index('ix_export_profiles_org', table_name='export_profiles')
    op.drop_table('export_profiles')
    op.drop_index(op.f('ix_dgii_submissions_tenant_id'), table_name='dgii_submissions')
    op.drop_index(op.f('ix_dgii_submissions_period'), table_name='dgii_submissions')
    op.drop_index(op.f('ix_dgii_submissions_organization_id'), table_name='dgii_submissions')
    op.drop_index('ix_dgii_submissions_lookup', table_name='dgii_submissions')
    op.drop_table('dgii_submissions')
    op.drop_index(op.f('ix_account_mappings_tenant_id'), table_name='account_mappings')
    op.drop_index(op.f('ix_account_mappings_provider'), table_name='account_mappings')
    op.drop_index(op.f('ix_account_mappings_organization_id'), table_name='account_mappings')
    op.drop_index('ix_account_mappings_org_provider', table_name='account_mappings')
    op.drop_table('account_mappings')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_refdata_domain_code', table_name='reference_data')
    op.drop_index('ix_refdata_domain', table_name='reference_data')
    op.drop_table('reference_data')
    op.drop_index(op.f('ix_integration_connections_tenant_id'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_provider'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_organization_id'), table_name='integration_connections')
    op.drop_index('ix_intconn_org_provider', table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index('ix_auditlog_visibility', table_name='audit_logs')
    op.drop_index('ix_auditlog_org_tenant', table_name='audit_logs')
    op.drop_index('ix_auditlog_created', table_name='audit_logs')
    op.drop_index('ix_auditlog_actor', table_name='audit_logs')
    op.drop_index('ix_auditlog_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_visibility'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
