"""create_metrics_snapshots_table

Revision ID: 5d9c4e2c4b8d
Revises: 67d08a7b0445
Create Date: 2026-06-14 21:53:08.002021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9c4e2c4b8d'
down_revision: Union[str, Sequence[str], None] = '67d08a7b0445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('mrr_cents', sa.Integer(), nullable=False),
    sa.Column('active_subscriptions_count', sa.Integer(), nullable=False),
    sa.Column('plan_distribution', sa.JSON(), nullable=False),
    sa.Column('status_distribution', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_snapshots_id'), 'metrics_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_snapshots_snapshot_date'), 'metrics_snapshots', ['snapshot_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_snapshots_snapshot_date'), table_name='metrics_snapshots')
    op.drop_index(op.f('ix_metrics_snapshots_id'), table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    # ### end Alembic commands ###
