"""add_is_ecf_authorized_to_organization

Revision ID: 5eeede167873
Revises: c7734be7b2e1
Create Date: 2026-05-26 12:39:20.054860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eeede167873'
down_revision: Union[str, Sequence[str], None] = 'c7734be7b2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('organizations', sa.Column('is_ecf_authorized', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_ecf_authorized')
    # ### end Alembic commands ###
