"""add_is_ecf_authorized_to_organization

Revision ID: 5eeede167873
Revises: c7734be7b2e1
Create Date: 2026-05-26 12:39:20.054860

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5eeede167873'
down_revision: Union[str, Sequence[str], None] = 'c7734be7b2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS is_ecf_authorized BOOLEAN DEFAULT false NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE organizations DROP COLUMN IF EXISTS is_ecf_authorized")
    # ### end Alembic commands ###
