"""create_tenant_vendor_rules_table

Revision ID: 633ffcf12c0c
Revises: 4064f55f9792
Create Date: 2026-05-24 14:19:00.096050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '633ffcf12c0c'
down_revision: Union[str, Sequence[str], None] = '4064f55f9792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_vendor_rules',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('emisor_rnc', sa.String(), nullable=False),
    sa.Column('dgii_category_code', sa.String(length=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'emisor_rnc', name='uq_tenant_vendor_rule')
    )
    op.create_index(op.f('ix_tenant_vendor_rules_tenant_id'), 'tenant_vendor_rules', ['tenant_id'], unique=False)
    op.create_index('ix_tvr_emisor_rnc', 'tenant_vendor_rules', ['emisor_rnc'], unique=False)
    op.create_index('ix_auditlog_visibility', 'audit_logs', ['visibility'], unique=False)
    op.alter_column('integration_connections', 'last_error',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('invitations', 'permissions',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('invitations', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('invitations_token_key'), 'invitations', type_='unique')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.alter_column('invoice_dgii_statuses', 'report_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('invoice_dgii_statuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_dgii_statuses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_inv_dgii_status_invoice_id'), table_name='invoice_dgii_statuses')
    op.drop_index(op.f('ix_inv_dgii_status_submission_id'), table_name='invoice_dgii_statuses')
    op.create_index(op.f('ix_invoice_dgii_statuses_invoice_id'), 'invoice_dgii_statuses', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_dgii_statuses_period'), 'invoice_dgii_statuses', ['period'], unique=False)
    op.create_index(op.f('ix_invoice_dgii_statuses_submission_id'), 'invoice_dgii_statuses', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_dgii_statuses_submission_id'), table_name='invoice_dgii_statuses')
    op.drop_index(op.f('ix_invoice_dgii_statuses_period'), table_name='invoice_dgii_statuses')
    op.drop_index(op.f('ix_invoice_dgii_statuses_invoice_id'), table_name='invoice_dgii_statuses')
    op.create_index(op.f('ix_inv_dgii_status_submission_id'), 'invoice_dgii_statuses', ['submission_id'], unique=False)
    op.create_index(op.f('ix_inv_dgii_status_invoice_id'), 'invoice_dgii_statuses', ['invoice_id'], unique=False)
    op.alter_column('invoice_dgii_statuses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_dgii_statuses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_dgii_statuses', 'report_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=False)
    op.create_unique_constraint(op.f('invitations_token_key'), 'invitations', ['token'])
    op.alter_column('invitations', 'accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('invitations', 'permissions',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('integration_connections', 'last_error',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index('ix_auditlog_visibility', table_name='audit_logs')
    op.drop_index('ix_tvr_emisor_rnc', table_name='tenant_vendor_rules')
    op.drop_index(op.f('ix_tenant_vendor_rules_tenant_id'), table_name='tenant_vendor_rules')
    op.drop_table('tenant_vendor_rules')
    # ### end Alembic commands ###
