"""add_alanube_telemetry

Revision ID: 67d08a7b0445
Revises: b1c2d3e4f5a6
Create Date: 2026-06-14 17:05:57.096829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import GUID


# revision identifiers, used by Alembic.
revision: str = '67d08a7b0445'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alanube_telemetry',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('tenant_id', GUID(length=32), nullable=False),
    sa.Column('organization_id', GUID(length=32), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ecf_type', sa.String(length=2), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alanube_telemetry_action'), 'alanube_telemetry', ['action'], unique=False)
    op.create_index(op.f('ix_alanube_telemetry_created_at'), 'alanube_telemetry', ['created_at'], unique=False)
    op.create_index(op.f('ix_alanube_telemetry_ecf_type'), 'alanube_telemetry', ['ecf_type'], unique=False)
    op.create_index(op.f('ix_alanube_telemetry_organization_id'), 'alanube_telemetry', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alanube_telemetry_success'), 'alanube_telemetry', ['success'], unique=False)
    op.create_index(op.f('ix_alanube_telemetry_tenant_id'), 'alanube_telemetry', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alanube_telemetry_tenant_id'), table_name='alanube_telemetry')
    op.drop_index(op.f('ix_alanube_telemetry_success'), table_name='alanube_telemetry')
    op.drop_index(op.f('ix_alanube_telemetry_organization_id'), table_name='alanube_telemetry')
    op.drop_index(op.f('ix_alanube_telemetry_ecf_type'), table_name='alanube_telemetry')
    op.drop_index(op.f('ix_alanube_telemetry_created_at'), table_name='alanube_telemetry')
    op.drop_index(op.f('ix_alanube_telemetry_action'), table_name='alanube_telemetry')
    op.drop_table('alanube_telemetry')
    # ### end Alembic commands ###
