"""add_user_id_and_plan_id_to_mio_payment_orders

Revision ID: 797fa8328aa8
Revises: 3d4e5f6a7b8c
Create Date: 2026-06-27 22:59:28.227089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '797fa8328aa8'
down_revision: Union[str, Sequence[str], None] = '3d4e5f6a7b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mio_payment_orders', sa.Column('user_id', app.database.GUID(length=32), nullable=True))
    op.add_column('mio_payment_orders', sa.Column('plan_id', app.database.GUID(length=32), nullable=True))
    op.alter_column('mio_payment_orders', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'mio_payment_orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'mio_payment_orders', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_organization_subscriptions_paddle_customer_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_paddle_subscription_id'), table_name='organization_subscriptions')
    op.drop_column('organization_subscriptions', 'paddle_customer_id')
    op.drop_column('organization_subscriptions', 'paddle_scheduled_change')
    op.drop_column('organization_subscriptions', 'paddle_subscription_id')
    op.drop_column('organization_subscriptions', 'paddle_collection_mode')
    op.drop_column('organization_subscriptions', 'paddle_price_id')
    op.drop_column('subscription_plans', 'paddle_price_id_monthly')
    op.drop_column('subscription_plans', 'paddle_product_id')
    op.drop_column('subscription_plans', 'paddle_price_id_annual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('paddle_price_id_annual', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('subscription_plans', sa.Column('paddle_product_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('subscription_plans', sa.Column('paddle_price_id_monthly', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('organization_subscriptions', sa.Column('paddle_price_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('organization_subscriptions', sa.Column('paddle_collection_mode', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('organization_subscriptions', sa.Column('paddle_subscription_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('organization_subscriptions', sa.Column('paddle_scheduled_change', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('organization_subscriptions', sa.Column('paddle_customer_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_organization_subscriptions_paddle_subscription_id'), 'organization_subscriptions', ['paddle_subscription_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_paddle_customer_id'), 'organization_subscriptions', ['paddle_customer_id'], unique=False)
    op.drop_constraint(None, 'mio_payment_orders', type_='foreignkey')
    op.drop_constraint(None, 'mio_payment_orders', type_='foreignkey')
    op.alter_column('mio_payment_orders', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('mio_payment_orders', 'plan_id')
    op.drop_column('mio_payment_orders', 'user_id')
    # ### end Alembic commands ###
