"""add_pending_uploads_table

Revision ID: 89a253842393
Revises: 633ffcf12c0c
Create Date: 2026-05-24 16:12:14.342750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '89a253842393'
down_revision: Union[str, Sequence[str], None] = '633ffcf12c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_uploads',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('user_id', app.database.GUID(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_uploads_organization_id'), 'pending_uploads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pending_uploads_tenant_id'), 'pending_uploads', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pending_uploads_user_id'), 'pending_uploads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_uploads_user_id'), table_name='pending_uploads')
    op.drop_index(op.f('ix_pending_uploads_tenant_id'), table_name='pending_uploads')
    op.drop_index(op.f('ix_pending_uploads_organization_id'), table_name='pending_uploads')
    op.drop_table('pending_uploads')
    # ### end Alembic commands ###
