"""create_upload_links_table

Revision ID: 89b35633dc35
Revises: f8a1b2c3d4e5
Create Date: 2026-06-05 22:13:20.793863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.database

# revision identifiers, used by Alembic.
revision: str = '89b35633dc35'
down_revision: Union[str, Sequence[str], None] = 'f8a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_links',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('created_by_user_id', app.database.GUID(length=32), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('max_files', sa.Integer(), nullable=False),
    sa.Column('uploaded_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_upload_links_organization_id ON upload_links (organization_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_upload_links_tenant_id ON upload_links (tenant_id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_upload_links_token ON upload_links (token)")
    # Idempotent drops — use IF EXISTS to avoid transaction abortion
    op.execute("ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_temporary_link_id_fkey")
    op.execute("ALTER TABLE invoices DROP COLUMN IF EXISTS temporary_link_id")
    op.execute("DROP INDEX IF EXISTS ix_temporary_links_created_by")
    op.execute("DROP INDEX IF EXISTS ix_temporary_links_organization_id")
    op.execute("DROP INDEX IF EXISTS ix_temporary_links_tenant_id")
    op.execute("DROP INDEX IF EXISTS ix_temporary_links_tenant_org")
    op.execute("DROP INDEX IF EXISTS ix_temporary_links_token")
    op.execute("DROP INDEX IF EXISTS ix_temporary_links_user_id")
    op.execute("DROP TABLE IF EXISTS temporary_links CASCADE")
    op.execute("ALTER TABLE ledger_entries ADD COLUMN IF NOT EXISTS currency VARCHAR(3) NOT NULL DEFAULT 'DOP'")
    op.alter_column('ledger_entries', 'entry_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('ledger_entries', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ledger_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.execute("DROP INDEX IF EXISTS ix_le_credit_note")
    op.execute("DROP INDEX IF EXISTS ix_le_invoice")
    op.execute("DROP INDEX IF EXISTS ix_le_reversal_of")
    op.execute("DROP INDEX IF EXISTS ix_le_tenant_org")
    op.execute("DROP INDEX IF EXISTS ix_ledger_bank_account")
    op.execute("DROP INDEX IF EXISTS ix_ledger_created_at")
    op.execute("DROP INDEX IF EXISTS ix_ledger_invoice")
    op.execute("DROP INDEX IF EXISTS ix_ledger_tenant_org")
    op.execute("CREATE INDEX IF NOT EXISTS ix_ledger_entries_credit_note_id ON ledger_entries (credit_note_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_ledger_entries_invoice_id ON ledger_entries (invoice_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_ledger_entries_organization_id ON ledger_entries (organization_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_ledger_entries_reversal_of ON ledger_entries (reversal_of)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_ledger_entries_tenant_id ON ledger_entries (tenant_id)")
    op.execute("ALTER TABLE ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_tenant_id_fkey")
    op.execute("ALTER TABLE ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_organization_id_fkey")
    op.execute("ALTER TABLE ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_reversed_entry_id_fkey")
    op.execute("ALTER TABLE ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_bank_account_id_fkey")
    op.execute("ALTER TABLE ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_created_by_fkey")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'ledger_entries'::regclass
                AND conname = 'fk_ledger_entries_tenant_id'
            ) THEN
                ALTER TABLE ledger_entries
                ADD CONSTRAINT fk_ledger_entries_tenant_id
                FOREIGN KEY (tenant_id) REFERENCES tenants(id);
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'ledger_entries'::regclass
                AND conname = 'fk_ledger_entries_organization_id'
            ) THEN
                ALTER TABLE ledger_entries
                ADD CONSTRAINT fk_ledger_entries_organization_id
                FOREIGN KEY (organization_id) REFERENCES organizations(id);
            END IF;
        END $$;
    """)
    op.execute("ALTER TABLE ledger_entries DROP COLUMN IF EXISTS reference")
    op.execute("ALTER TABLE ledger_entries DROP COLUMN IF EXISTS reversed_entry_id")
    op.execute("ALTER TABLE ledger_entries DROP COLUMN IF EXISTS bank_account_id")
    op.execute("ALTER TABLE ledger_entries DROP COLUMN IF EXISTS running_balance")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('running_balance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('ledger_entries', sa.Column('bank_account_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('ledger_entries', sa.Column('reversed_entry_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('ledger_entries', sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.execute("ALTER TABLE ledger_entries DROP CONSTRAINT IF EXISTS fk_ledger_entries_tenant_id")
    op.execute("ALTER TABLE ledger_entries DROP CONSTRAINT IF EXISTS fk_ledger_entries_organization_id")
    op.create_foreign_key(op.f('ledger_entries_created_by_fkey'), 'ledger_entries', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('ledger_entries_bank_account_id_fkey'), 'ledger_entries', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ledger_entries_reversed_entry_id_fkey'), 'ledger_entries', 'ledger_entries', ['reversed_entry_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('ledger_entries_organization_id_fkey'), 'ledger_entries', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ledger_entries_tenant_id_fkey'), 'ledger_entries', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ledger_entries_tenant_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_reversal_of'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_organization_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_invoice_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_credit_note_id'), table_name='ledger_entries')
    op.create_index(op.f('ix_ledger_tenant_org'), 'ledger_entries', ['tenant_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_ledger_invoice'), 'ledger_entries', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_ledger_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_bank_account'), 'ledger_entries', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_le_tenant_org'), 'ledger_entries', ['tenant_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_le_reversal_of'), 'ledger_entries', ['reversal_of'], unique=False)
    op.create_index(op.f('ix_le_invoice'), 'ledger_entries', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_le_credit_note'), 'ledger_entries', ['credit_note_id'], unique=False)
    op.alter_column('ledger_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ledger_entries', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('ledger_entries', 'entry_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('ledger_entries', 'currency')
    op.add_column('invoices', sa.Column('temporary_link_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invoices_temporary_link_id_fkey'), 'invoices', 'temporary_links', ['temporary_link_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'credit_notes', type_='foreignkey')
    op.drop_constraint(None, 'credit_notes', type_='foreignkey')
    op.create_foreign_key(op.f('credit_notes_organization_id_fkey'), 'credit_notes', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('credit_notes_deleted_by_fkey'), 'credit_notes', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('credit_notes_created_by_fkey'), 'credit_notes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('credit_notes_linked_by_fkey'), 'credit_notes', 'users', ['linked_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('credit_notes_tenant_id_fkey'), 'credit_notes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_credit_notes_tenant_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_status'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_organization_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_ncf_modified'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_is_deleted'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_invoice_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_deleted_at'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_number'), table_name='credit_notes')
    op.create_index(op.f('uq_cn_tenant_org_ncf'), 'credit_notes', ['tenant_id', 'organization_id', 'credit_note_number'], unique=True, postgresql_where='((credit_note_number IS NOT NULL) AND (is_deleted = false))')
    op.create_index(op.f('ix_cn_is_deleted'), 'credit_notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_cn_deleted_at'), 'credit_notes', ['deleted_at'], unique=False)
    op.create_table('temporary_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('max_uploads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploads_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('temporary_links_created_by_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('temporary_links_organization_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('temporary_links_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('temporary_links_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('temporary_links_pkey'))
    )
    op.create_index(op.f('ix_temporary_links_user_id'), 'temporary_links', ['user_id'], unique=False)
    op.create_index(op.f('ix_temporary_links_token'), 'temporary_links', ['token'], unique=True)
    op.create_index(op.f('ix_temporary_links_tenant_org'), 'temporary_links', ['tenant_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_temporary_links_tenant_id'), 'temporary_links', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_temporary_links_organization_id'), 'temporary_links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_temporary_links_created_by'), 'temporary_links', ['created_by'], unique=False)
    op.drop_index(op.f('ix_upload_links_token'), table_name='upload_links')
    op.drop_index(op.f('ix_upload_links_tenant_id'), table_name='upload_links')
    op.drop_index(op.f('ix_upload_links_organization_id'), table_name='upload_links')
    op.drop_table('upload_links')
    # ### end Alembic commands ###
