"""add_billing_models

Revision ID: 98a49772a04b
Revises: b776fa27a514
Create Date: 2026-05-25 23:36:10.002090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision: str = '98a49772a04b'
down_revision: Union[str, Sequence[str], None] = 'b776fa27a514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clients_tax_id'), 'clients', ['tax_id'], unique=False)
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.create_index('ix_clients_tenant_org', 'clients', ['tenant_id', 'organization_id'], unique=False)
    op.create_table('ecf_sequences',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('ecf_type', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecf_sequences_is_active'), 'ecf_sequences', ['is_active'], unique=False)
    op.create_index(op.f('ix_ecf_sequences_organization_id'), 'ecf_sequences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ecf_sequences_tenant_id'), 'ecf_sequences', ['tenant_id'], unique=False)
    op.create_index('ix_ecf_sequences_tenant_org', 'ecf_sequences', ['tenant_id', 'organization_id'], unique=False)
    op.create_index('ix_ecf_sequences_type', 'ecf_sequences', ['tenant_id', 'organization_id', 'ecf_type'], unique=False)
    op.create_table('products',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('internal_code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_code', 'products', ['tenant_id', 'organization_id', 'internal_code'], unique=False)
    op.create_index(op.f('ix_products_internal_code'), 'products', ['internal_code'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_index('ix_products_tenant_org', 'products', ['tenant_id', 'organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tenant_org', table_name='products')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_internal_code'), table_name='products')
    op.drop_index('ix_products_code', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_ecf_sequences_type', table_name='ecf_sequences')
    op.drop_index('ix_ecf_sequences_tenant_org', table_name='ecf_sequences')
    op.drop_index(op.f('ix_ecf_sequences_tenant_id'), table_name='ecf_sequences')
    op.drop_index(op.f('ix_ecf_sequences_organization_id'), table_name='ecf_sequences')
    op.drop_index(op.f('ix_ecf_sequences_is_active'), table_name='ecf_sequences')
    op.drop_table('ecf_sequences')
    op.drop_index('ix_clients_tenant_org', table_name='clients')
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_tax_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
