"""drop_mio_payments

Revision ID: 9e884bd4ddb2
Revises: f2b3c4d5e6f7
Create Date: 2026-06-20 22:20:22.825472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e884bd4ddb2'
down_revision: Union[str, Sequence[str], None] = 'f2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mio_payments_invoice_id'), table_name='mio_payments')
    op.drop_index(op.f('ix_mio_payments_mio_order_uuid'), table_name='mio_payments')
    op.drop_index(op.f('ix_mio_payments_organization_id'), table_name='mio_payments')
    op.drop_index(op.f('ix_mio_payments_status'), table_name='mio_payments')
    op.drop_index(op.f('ix_mio_payments_tenant_id'), table_name='mio_payments')
    op.drop_table('mio_payments')
    op.alter_column('organization_subscriptions', 'paddle_scheduled_change',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('organization_subscriptions', 'addon_billing_entities',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('paddle_webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint(op.f('paddle_webhook_events_event_id_key'), 'paddle_webhook_events', type_='unique')
    op.drop_index(op.f('ix_paddle_webhook_events_event_id'), table_name='paddle_webhook_events')
    op.create_index(op.f('ix_paddle_webhook_events_event_id'), 'paddle_webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paddle_webhook_events_event_id'), table_name='paddle_webhook_events')
    op.create_index(op.f('ix_paddle_webhook_events_event_id'), 'paddle_webhook_events', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('paddle_webhook_events_event_id_key'), 'paddle_webhook_events', ['event_id'])
    op.alter_column('paddle_webhook_events', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('organization_subscriptions', 'addon_billing_entities',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organization_subscriptions', 'paddle_scheduled_change',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('mio_payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('mio_order_uuid', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('checkout_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('authorization_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('webhook_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('mio_payments_invoice_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('mio_payments_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('mio_payments_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mio_payments_pkey'))
    )
    op.create_index(op.f('ix_mio_payments_tenant_id'), 'mio_payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mio_payments_status'), 'mio_payments', ['status'], unique=False)
    op.create_index(op.f('ix_mio_payments_organization_id'), 'mio_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mio_payments_mio_order_uuid'), 'mio_payments', ['mio_order_uuid'], unique=True)
    op.create_index(op.f('ix_mio_payments_invoice_id'), 'mio_payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###
