"""add_upload_link_id_to_invoice

Revision ID: a49880f821eb
Revises: 465d130b62a0
Create Date: 2026-06-06 13:45:27.115135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import GUID


# revision identifiers, used by Alembic.
revision: str = 'a49880f821eb'
down_revision: Union[str, Sequence[str], None] = '465d130b62a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('upload_link_id', GUID(length=32), nullable=True))
    op.create_index(op.f('ix_invoices_upload_link_id'), 'invoices', ['upload_link_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'upload_links', ['upload_link_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_upload_link_id'), table_name='invoices')
    op.drop_column('invoices', 'upload_link_id')
    # ### end Alembic commands ###
