"""add_mio_payments

Revision ID: a5102aa346de
Revises: a49880f821ec
Create Date: 2026-06-09 15:12:55.208249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'a5102aa346de'
down_revision: Union[str, Sequence[str], None] = 'a49880f821ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mio_payments',
    sa.Column('id', app.database.GUID(length=32), nullable=False),
    sa.Column('tenant_id', app.database.GUID(length=32), nullable=False),
    sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
    sa.Column('invoice_id', app.database.GUID(length=32), nullable=True),
    sa.Column('mio_order_uuid', sa.String(length=100), nullable=False),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('authorization_code', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('webhook_payload', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mio_payments_invoice_id'), 'mio_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_mio_payments_mio_order_uuid'), 'mio_payments', ['mio_order_uuid'], unique=True)
    op.create_index(op.f('ix_mio_payments_organization_id'), 'mio_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mio_payments_status'), 'mio_payments', ['status'], unique=False)
    op.create_index(op.f('ix_mio_payments_tenant_id'), 'mio_payments', ['tenant_id'], unique=False)
    op.alter_column('invoices', 'modification_reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.create_index(op.f('ix_invoices_parent_invoice_id'), 'invoices', ['parent_invoice_id'], unique=False)
    op.drop_index(op.f('ix_ledger_entries_credit_note_id'), table_name='ledger_entries')
    op.create_index(op.f('ix_ledger_entries_modificatory_invoice_id'), 'ledger_entries', ['modificatory_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_modificatory_invoice_id'), table_name='ledger_entries')
    op.create_index(op.f('ix_ledger_entries_credit_note_id'), 'ledger_entries', ['modificatory_invoice_id'], unique=False)
    op.drop_index(op.f('ix_invoices_parent_invoice_id'), table_name='invoices')
    op.alter_column('invoices', 'modification_reason',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_mio_payments_tenant_id'), table_name='mio_payments')
    op.drop_index(op.f('ix_mio_payments_status'), table_name='mio_payments')
    op.drop_index(op.f('ix_mio_payments_organization_id'), table_name='mio_payments')
    op.drop_index(op.f('ix_mio_payments_mio_order_uuid'), table_name='mio_payments')
    op.drop_index(op.f('ix_mio_payments_invoice_id'), table_name='mio_payments')
    op.drop_table('mio_payments')
    # ### end Alembic commands ###
