"""add_bank_account_to_invoice

Revision ID: b776fa27a514
Revises: 31742cdfd5f5
Create Date: 2026-05-25 17:18:08.668125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import GUID


# revision identifiers, used by Alembic.
revision: str = 'b776fa27a514'
down_revision: Union[str, Sequence[str], None] = '31742cdfd5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS bank_account_id UUID")
    # Create FK only if it doesn't already exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE table_name = 'invoices' 
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%bank_account_id%'
            ) THEN
                ALTER TABLE invoices ADD CONSTRAINT invoices_bank_account_id_fkey 
                FOREIGN KEY (bank_account_id) REFERENCES bank_accounts(id) ON DELETE SET NULL;
            END IF;
        END
        $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_bank_account_id_fkey")
    op.execute("ALTER TABLE invoices DROP COLUMN IF EXISTS bank_account_id")
    # ### end Alembic commands ###
