"""add_bank_account_to_invoice

Revision ID: b776fa27a514
Revises: 31742cdfd5f5
Create Date: 2026-05-25 17:18:08.668125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import GUID


# revision identifiers, used by Alembic.
revision: str = 'b776fa27a514'
down_revision: Union[str, Sequence[str], None] = '31742cdfd5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('bank_account_id', GUID(length=32), nullable=True))
    op.create_foreign_key(None, 'invoices', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'bank_account_id')
    # ### end Alembic commands ###
