"""rename_client_tax_id_compound_index

Revision ID: c7734be7b2e1
Revises: 98a49772a04b
Create Date: 2026-05-25 23:39:43.712738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7734be7b2e1'
down_revision: Union[str, Sequence[str], None] = '98a49772a04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE INDEX IF NOT EXISTS ix_clients_tenant_org_tax_id ON clients (tenant_id, organization_id, tax_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_clients_tenant_org_tax_id")
    # ### end Alembic commands ###
