"""add_is_deleted_to_organization

Revision ID: d76728d55ef4
Revises: 5d9c4e2c4b8d
Create Date: 2026-06-14 22:23:17.621385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76728d55ef4'
down_revision: Union[str, Sequence[str], None] = '5d9c4e2c4b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_deleted')
    # ### end Alembic commands ###
