"""add_subscription_and_usage_tables

Revision ID: dc5fa79d59cd
Revises: 9f0e1d2c3b4a
Create Date: 2026-06-03 06:57:15.540367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
import app


# revision identifiers, used by Alembic.
revision: str = 'dc5fa79d59cd'
down_revision: Union[str, Sequence[str], None] = '9f0e1d2c3b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not inspect(bind).has_table('subscription_plans'):
        op.create_table('subscription_plans',
            sa.Column('id', app.database.GUID(length=32), nullable=False),
            sa.Column('name', sa.String(length=64), nullable=False),
            sa.Column('display_name', sa.String(length=128), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('price_monthly_cents', sa.Integer(), nullable=False),
            sa.Column('currency', sa.String(length=3), nullable=True),
            sa.Column('extra_entity_price_cents', sa.Integer(), nullable=True),
            sa.Column('addon_ecf_block_size', sa.Integer(), nullable=True),
            sa.Column('addon_ecf_block_price_cents', sa.Integer(), nullable=True),
            sa.Column('addon_ai_block_size', sa.Integer(), nullable=True),
            sa.Column('addon_ai_block_price_cents', sa.Integer(), nullable=True),
            sa.Column('addon_storage_block_mb', sa.Integer(), nullable=True),
            sa.Column('addon_storage_block_price_cents', sa.Integer(), nullable=True),
            sa.Column('max_users', sa.Integer(), nullable=False),
            sa.Column('max_entities', sa.Integer(), nullable=False),
            sa.Column('max_ecf_monthly', sa.Integer(), nullable=False),
            sa.Column('max_ai_queries_monthly', sa.Integer(), nullable=False),
            sa.Column('max_ocr_docs_monthly', sa.Integer(), nullable=False),
            sa.Column('max_storage_mb', sa.Integer(), nullable=False),
            sa.Column('max_api_calls_monthly', sa.Integer(), nullable=True),
            sa.Column('max_ai_rate_per_minute', sa.Integer(), nullable=False),
            sa.Column('max_api_rate_per_minute', sa.Integer(), nullable=False),
            sa.Column('max_ocr_rate_per_minute', sa.Integer(), nullable=False),
            sa.Column('has_advanced_reports', sa.Boolean(), nullable=True),
            sa.Column('has_api_access', sa.Boolean(), nullable=True),
            sa.Column('has_webhooks', sa.Boolean(), nullable=True),
            sa.Column('has_sla', sa.Boolean(), nullable=True),
            sa.Column('has_ai_sidebar', sa.Boolean(), nullable=True),
            sa.Column('has_multi_entity_dashboard', sa.Boolean(), nullable=True),
            sa.Column('has_cross_company_history', sa.Boolean(), nullable=True),
            sa.Column('has_batch_ecf_generation', sa.Boolean(), nullable=True),
            sa.Column('soft_limit_enabled', sa.Boolean(), nullable=True),
            sa.Column('overage_unit_price_cents', sa.Integer(), nullable=True),
            sa.Column('sort_order', sa.Integer(), nullable=True),
            sa.Column('is_public', sa.Boolean(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('is_enterprise', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    if not inspect(bind).has_table('organization_subscriptions'):
        op.create_table('organization_subscriptions',
            sa.Column('id', app.database.GUID(length=32), nullable=False),
            sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
            sa.Column('plan_id', app.database.GUID(length=32), nullable=False),
            sa.Column('status', sa.String(length=32), nullable=False),
            sa.Column('billing_cycle_start', sa.DateTime(timezone=True), nullable=False),
            sa.Column('billing_cycle_end', sa.DateTime(timezone=True), nullable=False),
            sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('addon_ecf_blocks', sa.Integer(), nullable=True),
            sa.Column('addon_ai_blocks', sa.Integer(), nullable=True),
            sa.Column('addon_storage_blocks', sa.Integer(), nullable=True),
            sa.Column('addon_extra_entities', sa.Integer(), nullable=True),
            sa.Column('auto_renew_addons', sa.Boolean(), nullable=True),
            sa.Column('custom_limits_json', sa.String(), nullable=True),
            sa.Column('custom_price_cents', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
            sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=False)
    if not inspect(bind).has_table('usage_records'):
        op.create_table('usage_records',
            sa.Column('id', app.database.GUID(length=32), nullable=False),
            sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
            sa.Column('cycle', sa.Integer(), nullable=False),
            sa.Column('ecf_count', sa.Integer(), nullable=False),
            sa.Column('ai_query_count', sa.Integer(), nullable=False),
            sa.Column('ocr_doc_count', sa.Integer(), nullable=False),
            sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
            sa.Column('api_call_count', sa.Integer(), nullable=False),
            sa.Column('soft_limit_80pct_notified', sa.Boolean(), nullable=True),
            sa.Column('soft_limit_100pct_notified', sa.Boolean(), nullable=True),
            sa.Column('overage_detected', sa.Boolean(), nullable=True),
            sa.Column('overage_units', sa.Integer(), nullable=True),
            sa.Column('overage_amount_cents', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_usage_records_organization_id'), 'usage_records', ['organization_id'], unique=False)
        op.create_index(op.f('ix_usage_records_cycle'), 'usage_records', ['cycle'], unique=False)
    if not inspect(bind).has_table('usage_alerts'):
        op.create_table('usage_alerts',
            sa.Column('id', app.database.GUID(length=32), nullable=False),
            sa.Column('organization_id', app.database.GUID(length=32), nullable=False),
            sa.Column('alert_type', sa.String(length=64), nullable=False),
            sa.Column('cycle', sa.Integer(), nullable=False),
            sa.Column('message', sa.String(length=512), nullable=False),
            sa.Column('pct_used', sa.Integer(), nullable=True),
            sa.Column('current_usage', sa.Integer(), nullable=True),
            sa.Column('limit_value', sa.Integer(), nullable=True),
            sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('acknowledged', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_usage_alerts_organization_id'), 'usage_alerts', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_alerts_organization_id'), table_name='usage_alerts')
    op.drop_table('usage_alerts')
    op.drop_index(op.f('ix_usage_records_cycle'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_organization_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
