"""add_municipality_province_to_org

Revision ID: e76f5b7bbbee
Revises: 9f0e1d2c3b4a
Create Date: 2026-05-29 12:12:13.833304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76f5b7bbbee'
down_revision: Union[str, Sequence[str], None] = '9f0e1d2c3b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('municipality', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('province', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'province')
    op.drop_column('organizations', 'municipality')
    # ### end Alembic commands ###
