"""add_cart_items_json_to_mio_payment_orders

Revision ID: f792438e9fa1
Revises: dfaeba717c69
Create Date: 2026-06-29 13:35:44.477951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f792438e9fa1'
down_revision: Union[str, Sequence[str], None] = 'dfaeba717c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mio_payment_orders', sa.Column('cart_items_json', sa.JSON(), nullable=True))
    op.alter_column('user_subscriptions', 'addon_entity_slots',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'addon_entity_slots',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('mio_payment_orders', 'cart_items_json')
    # ### end Alembic commands ###
